-- cosmo knowledge map — generated by scripts/gen_project_map.mjs (do not edit by hand).
-- Rich per-project Obsidian map. Idempotent: clears this project's map then
-- reinserts with deterministic UUIDv5 ids.

delete from map_edges where project_id = '00000000-0000-0000-0000-00000000a006';
delete from map_nodes where project_id = '00000000-0000-0000-0000-00000000a006';

insert into map_nodes (id, org_id, project_id, label, kind, note) values
  ('ab118257-cbe5-5b47-bf43-2b47153184ae','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masteri Cosmo Central','project','NEXUS ZONE · CT3–CT4

Chủ đầu tư: Masterise Homes® · Vị trí: Lõi The Global City, Đỗ Xuân Hợp, P. Bình Trưng · Quy mô: 6 tháp 19–29 tầng + 3 khối đế + 2 hầm · Loại hình: Căn hộ + Office + TMDV · Sản phẩm: 1PN → 4PN, Penthouse, Duplex · Sở hữu: Lâu dài (khách quốc tịch VN) · Ra mắt: 15/01/2026 · Bàn giao dự kiến: Q3/2028

Masteri Cosmo Central là phân khu cao tầng mới nhất trong lõi The Global City — nằm tại CT3 + CT4 ngay trục Đỗ Xuân Hợp, được định vị là "trái tim" của khu đô thị. Gồm 6 tháp 19–29 tầng, 3 tầng khối đế thương mại và 2 tầng hầm kết nối. Sản phẩm chính cho phân khúc căn hộ cao cấp: 1PN/1PN+/2PN/2PN+/3PN/4PN, Penthouse, Duplex. Mặt bằng B1 (tầng 5–15) ~19 căn/sàn; B2 (tầng 12B–17) ~12 căn/sàn, view kênh đào nhạc nước và SOHO. Đây là dự án Masterise đầu tiên mở bán ngay vào "thời điểm vàng" hạ tầng khu Đông hội tụ 2026–2027, với lịch bàn giao Q3/2028 rơi đúng vào giai đoạn định giá lại của toàn khu vực.

★ Talking point: "Cosmo Central không bán một căn hộ — nó bán vị trí trái tim của khu đô thị duy nhất tại TP.HCM do Foster + Partners quy hoạch, ngay thời điểm hạ tầng khu Đông về đích đồng loạt."'),
  ('e6f4d1de-9eff-5fd4-8006-5ce6c392b885','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Phân khu Nexus Zone','project','Giao điểm của mọi kết nối

Định vị: Giao điểm của mọi kết nối · Slogan: Sống trọn vẹn từng nhịp cộng hưởng · Vị trí cụm: CT3–CT4 (Work-life Synergy)

Nexus Zone là tên phân khu mở bán của Masteri Cosmo Central — định vị "Giao điểm của mọi kết nối", hướng đến giới chuyên gia, doanh nhân, công dân toàn cầu đề cao cân bằng công việc – cuộc sống. Liền kề khu Office và trục thương mại, 2 bên là kênh đào nhạc nước. Đây là "thấu kính cộng hưởng" của phong cách sống thế hệ mới: con người – không gian – trải nghiệm.

★ Talking point: "Nexus = điểm hội tụ. Khách của Nexus Zone là người muốn sống ngay giao điểm: vừa cạnh chỗ làm, vừa cạnh kênh nhạc nước, vừa cạnh trung tâm thương mại."'),
  ('25d7515c-d8d0-5a8e-9460-d12e28db1347','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Thiết kế Terra Tropical','project','Ngôn ngữ kiến trúc

Phong cách: Nhiệt đới hiện đại, xếp lớp chuyển động · Đặc trưng: Ban công rộng, kính toàn cảnh kịch trần · Triết lý: Kết nối liền mạch trong – ngoài

Terra Tropical là ngôn ngữ thiết kế riêng của Cosmo Central — nhịp điệu đô thị gặp tinh thần nhiệt đới hiện đại. Kiến trúc xếp lớp nhiều tầng chuyển động, ban công rộng mở, hệ cửa kính toàn cảnh phóng tầm ra đại cảnh đô thị. Cộng hưởng giữa chuẩn sống Masteri Collection và hệ tiện ích quốc tế The Global City tạo nên không gian đa sắc.

★ Talking point: "Terra Tropical không phải kiểu hộp kính lạnh lẽo — nó là kiến trúc thở được, đón gió đón sáng, đúng tinh thần sống nhiệt đới nhưng chuẩn quốc tế."'),
  ('5a098ea5-5037-59e7-8581-133ec4abdd4e','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','29+ Tiện ích đặc quyền','project','23 ngoài trời + 6 trong nhà

Tổng: 23 tiện ích ngoài trời + 6 trong nhà · Hồ bơi: Vô cực + Jacuzzi + hồ trẻ em + nước nóng · Làm việc: Business lounge, Co-working, thư viện · Sức khoẻ: Gym, Yoga, sàn tắm nắng · Gia đình: Kid playground, Teen club, BBQ

Hệ tiện ích 23 ngoài trời + 6 trong nhà (một số tài liệu cộng gộp tiện ích The Global City thành "50+"). Nổi bật: hồ bơi vô cực + jacuzzi + hồ nước nóng, sảnh cư dân 5 sao mỗi tháp, Business Lounge, Co-working Space, thư viện, phòng Gym, phòng Yoga, Kid Playground, Teen Club, chòi BBQ, bến kayak trên kênh.

★ Talking point: "Cư dân có cả không gian làm việc (Business Lounge, Co-working) lẫn nghỉ ngơi (hồ vô cực, yoga, teen club) trong cùng một khối đế — đúng tinh thần work-life synergy của CT3–CT4."'),
  ('0a05e557-daa5-5014-9ffb-8d14ae3ee4a5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Chính sách khảo sát','project','Dự kiến — theo từng đợt CĐT

Đặt trước: 100 triệu/căn · Early Bird KH thường: -1% (đến hết 31/05/2026) · Cư dân Masterise: -2% · Hỗ trợ phí QL: 24 tháng · Vay HTLS: 70%, lãi suất 0% đến 31/10/2028 · Chiết khấu TT sớm: lên đến -11%

Chính sách khảo sát dự kiến (áp dụng theo từng thời điểm ban hành của CĐT). Đặt trước 100 triệu; Early Bird -1% (KH thường) / -2% (cư dân Masterise) đến hết 31/05/2026; hỗ trợ phí quản lý 24 tháng kể từ thông báo bàn giao. Các luồng thanh toán: theo tiến độ (HT -7%), thanh toán sớm (-9% đến -11%), vay vốn HTLS 70% lãi 0% đến 31/10/2028 (tối đa 6 tháng sau đủ điều kiện bàn giao).

★ Talking point: "Booking chỉ 100 triệu, early bird đến 31/5, cư dân Masterise thêm 2%, vay 0% lãi tới cuối 2028 — đòn bẩy này giúp khách giữ dòng tiền trong suốt giai đoạn hạ tầng về đích."'),
  ('96a36515-accc-5a3d-ab8c-10295f8a134e','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','◉ Xem phối cảnh 360°','project','Mở tab mới

Loại: Tương tác 360° tổng thể · Nguồn: masterisehomes.com

Trải nghiệm phối cảnh tổng thể The Global City dạng 360° tương tác — xoay toàn cảnh dự án, kênh đào nhạc nước, các phân khu và vị trí Masteri Cosmo Central. Nhấn nút bên dưới để mở trong tab mới.

★ Talking point: "Cho khách xoay 360° ngay trên màn hình — họ thấy được vị trí trái tim của Cosmo Central giữa toàn cảnh kênh nhạc nước và SOHO trước khi tới nhà mẫu."'),
  ('a7f489a9-22cb-5766-a5b2-c9056e48579c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masterise Group','group','Thành lập: 2007 (tiền thân Thảo Điền Investment) · Đổi tên: 2019 → Masterise Group · Vốn điều lệ: VND 6,727 tỷ → 35,200 tỷ (8/2025) · Chủ tịch: Hồ Anh Minh (sinh 1995, từ 13/1/2025) · Mảng: BĐS · Vận hành · Hospitality · Hạ tầng

Masterise Group (tiền thân CTCP Đầu tư Thảo Điền, 2007; đổi tên 2019) là tập đoàn tư nhân đa ngành. Vốn điều lệ được nâng từ VND 6,727 tỷ lên hơn 35,200 tỷ (8/2025) để phục vụ bước chuyển sang hạ tầng quốc gia. Hệ sinh thái: Masterise Homes (phát triển BĐS hàng hiệu), Masterise Property Management (vận hành), Masterise Hospitality & Entertainment (TTTM, sự kiện), Masterise Agents (phân phối), và các pháp nhân hạ tầng mới (hàng không, cầu).

★ Talking point: "Vốn điều lệ Masterise tăng gấp hơn 5 lần lên 35.200 tỷ chỉ trong một năm — đó là tín hiệu của một tập đoàn đang chuyển mình từ nhà phát triển BĐS thành nhà kiến tạo hạ tầng quốc gia."'),
  ('882a47f5-3631-55b8-9b0c-4dd6539132d8','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Hệ sinh thái Techcombank','group','Bên liên quan

Liên quan: Gia đình Chủ tịch Techcombank Hồ Hùng Anh · Sở hữu: Vợ + con trai Hồ Anh Minh > 10% mỗi người · Phó CT: Hồ Anh Ngọc

Theo Tuổi Trẻ (14/3/2025), Masterise Group là bên có liên quan đến Techcombank, do gia đình Chủ tịch Techcombank Hồ Hùng Anh chi phối: vợ (bà Nguyễn Thị Thanh Thủy) và con trai Hồ Anh Minh (sinh 1995) mỗi người sở hữu trên 10%; em trai Hồ Anh Ngọc là Phó Chủ tịch. Mối liên hệ này mang lại nền tảng tài chính và quản trị vững — yếu tố quan trọng cho cam kết bàn giao đúng hẹn.

★ Talking point: "Đứng sau Masterise là hệ sinh thái Techcombank — một trong những ngân hàng tư nhân lớn nhất Việt Nam. Năng lực tài chính này là bảo chứng cho tiến độ dự án."'),
  ('5efd62f3-2209-50ad-baac-f29bd057fc34','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masterise Property Mgmt','group','Vận hành chuẩn quốc tế

Vai trò: Vận hành & quản lý BĐS · Áp dụng: The Global City + Cosmo Central

Masterise Property Management vận hành và quản lý The Global City cũng như Masteri Cosmo Central theo tiêu chuẩn quốc tế — yếu tố giữ giá trị tài sản và chất lượng sống dài hạn.

★ Talking point: "Cùng một đơn vị vận hành đẳng cấp đang quản lý Grand Marina sẽ vận hành Cosmo Central — chuẩn dịch vụ không đổi."'),
  ('379ba9ad-fda6-5063-84b3-5b090650faa3','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masterise Hospitality & Ent.','group','TTTM · Sự kiện

Vai trò: TTTM, F&B, sự kiện tại The Global City

Mảng Hospitality & Entertainment vận hành trung tâm thương mại, F&B và chuỗi sự kiện quy mô lớn tại The Global City — biến khu đô thị thành điểm đến sống động (concert, lễ hội, thể thao).

★ Talking point: "Chính đội ngũ này tạo ra ATVCG, SOOBIN, Global Wishmas — biến The Global City thành nơi cả Sài Gòn đổ về, kéo theo giá trị cho cư dân."'),
  ('71536758-a0c3-5c7c-b748-ca4af52b3b74','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Cầu Phú Mỹ 2','group','Masterise đầu tư · TP.HCM–Đồng Nai

Tổng đầu tư: ~VND 23,186 tỷ · Quy mô: 8 làn, 6.3 km, dây văng 2 tầng đầu tiên TP.HCM · Tĩnh không: 55m (cao nhất nhóm) · Khởi công: 15/01/2026 · Kết nối: Nguyễn Hữu Thọ → Đường liên cảng Đồng Nai

Cầu Phú Mỹ 2 (~VND 23,186 tỷ, PPP) — cầu dây văng 2 tầng đầu tiên tại TP.HCM, 8 làn, 6.3 km, tĩnh không 55m. Khởi công 15/01/2026. Tạo trục nhanh Phú Mỹ Hưng → sân bay Long Thành. Đây là minh chứng cho năng lực hạ tầng của Masterise — không chỉ xây nhà mà xây cả huyết mạch giao thông quốc gia.

★ Talking point: "Masterise tự bỏ vốn xây cây cầu 23.000 tỷ kết nối TP.HCM – Đồng Nai. Một chủ đầu tư có thể làm hạ tầng quốc gia thì chuyện bàn giao đúng hẹn một dự án căn hộ là điều đương nhiên."'),
  ('e41c9ed7-ed76-59cc-9a09-96b77b269183','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Cầu Cần Giờ','group','Masterise nghiên cứu đầu tư

Tổng đầu tư: ~VND 13,200 tỷ · Quy mô: 6 làn, dây văng vượt sông Soài Rạp · Khởi công: 15/01/2026 (chính thức 3/6/2026) · Hoàn thành: 30/6/2029 · Thay thế: Phà Bình Khánh

Cầu Cần Giờ (~VND 13,200 tỷ, PPP) — phá thế độc đạo phà Bình Khánh, rút Nhà Bè – Cần Giờ từ 2 giờ xuống 40–50 phút. Khởi công 15/01/2026, hoàn thành 30/6/2029. Kiến trúc dây văng lấy cảm hứng cây đước.

★ Talking point: "Phú Mỹ 2, Cần Giờ, Gia Bình — ba dự án hạ tầng cùng một nhà đầu tư. Đó là tầm vóc của tập đoàn đứng sau Cosmo Central."'),
  ('faa80c96-4365-59a1-9897-d1dc5a7e98c4','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Sân bay QT Gia Bình','group','Masterise đầu tư · Bắc Ninh

Tổng đầu tư: ~VND 196,378 tỷ · Quy mô: ~1,960 ha, ICAO 4F, 2 đường băng 3,500m · Công suất 2030: 30 triệu khách + 1.6 triệu tấn · Công suất 2050: 50 triệu khách + 2.5 triệu tấn · Phê duyệt: Quốc hội — NQ 256/2025/QH15 (11/12/2025) · Pháp nhân: CTCP Hạ tầng HK Masterise (80%)

Cảng hàng không quốc tế Gia Bình (Bắc Ninh) — tổng đầu tư ~VND 196,378 tỷ, được Quốc hội thông qua chủ trương cho Masterise đầu tư ngày 11/12/2025 (NQ 256/2025/QH15). Công suất 30 triệu khách (2030) → 50 triệu (2050), chuẩn ICAO 4F, mục tiêu 5 sao Skytrax top-10 thế giới.

★ Talking point: "Quốc hội giao Masterise đầu tư siêu sân bay 196.000 tỷ. Đây là cấp độ tín nhiệm cao nhất một doanh nghiệp tư nhân có thể đạt được tại Việt Nam."'),
  ('b3118f66-71cd-5a63-9105-5a97cdbf493c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masterise Homes','brand','11 năm · 27+ dự án

Khởi đầu: 2014 — Masteri Thảo Điền · Quy mô: 27+ dự án đẳng cấp quốc tế · Phạm vi: HCM · Hà Nội · Hải Phòng · Đà Nẵng · 3 phân khúc: Branded Residences · LUMIÈRE · Masteri Collection

Masterise Homes® — nhà phát triển BĐS hàng hiệu tiên phong đưa chuẩn sống quốc tế về Việt Nam, hợp tác Marriott, Ritz-Carlton, JW Marriott, Elie Saab, Foster + Partners, WATG. Hành trình 11 năm từ Masteri Thảo Điền (2014) đến Masteri Cosmo Central (2026), dẫn dắt thị trường với 3 phân khúc: Branded Residences, LUMIÈRE Series, Masteri Collection.

★ Talking point: "11 năm, 27+ dự án, từ Masteri Thảo Điền đến Grand Marina. Cosmo Central kế thừa toàn bộ kinh nghiệm đó."'),
  ('d789b26b-cd06-5620-a387-ba98aa3c4107','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masteri Collection','brand','15 dự án · ~27,200 căn

Số dự án: 15 · Số căn: ~27,200 · Triết lý: Đô thị vị nhân sinh · Cosmo Central: thuộc dòng này

Masteri Collection là dòng sản phẩm cao cấp cốt lõi của Masterise Homes (15 dự án, ~27,200 căn) — mang triết lý "Đô thị vị nhân sinh", lấy con người làm trung tâm. Masteri Cosmo Central thuộc dòng này, thiết kế cho công dân toàn cầu hướng đến tiêu chuẩn sống quốc tế: kết nối toàn diện công việc – giáo dục – y tế – giải trí.

★ Talking point: "Masteri Collection = chuẩn sống quốc tế cho công dân toàn cầu. Cosmo Central là phiên bản mới nhất, đặt ngay trái tim The Global City."'),
  ('bd8209bb-d2d6-50f3-92a0-0dce42a1b578','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','LUMIÈRE Series','brand','8 dự án · ~14,500 căn

Số dự án: 8 · Số căn: ~14,500 · Tại TGC: LUMIÈRE Midtown

LUMIÈRE Series (8 dự án, ~14,500 căn) — dòng căn hộ cao cấp biểu tượng sống tinh anh. Tại The Global City có LUMIÈRE Midtown.

★ Talking point: "LUMIÈRE và Masteri Collection cùng tồn tại trong The Global City — cư dân Cosmo Central sống cạnh cả một hệ thương hiệu Masterise."'),
  ('22567a09-5af3-57d0-be5a-2123df44d8be','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Branded Residences','brand','3 dự án · ~14,500 căn

Số dự án: 3 · Gồm: Grand Marina · The Grand Hanoi · The Rivus

Phân khúc BĐS hàng hiệu quốc tế (3 dự án) đặt Masterise vào nhóm hiếm hoi toàn cầu: Grand Marina Saigon (Marriott & JW Marriott lớn nhất thế giới), The Grand Hanoi (Ritz-Carlton thứ 5 châu Á – TBD), The Rivus (121 dinh thự Elie Saab duy nhất VN).

★ Talking point: "Một chủ đầu tư làm được căn hộ hàng hiệu Marriott, Ritz-Carlton, Elie Saab thì chuẩn hoàn thiện ở Cosmo Central nằm trong cùng một hệ DNA."'),
  ('bbff31a8-7c0d-53b3-ab6a-4213c9e382af','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masteri Thảo Điền','brand','Chứng cứ tăng giá · 2014

Mở bán: 2014 @ ~35 triệu/m² · Hiện tại: ~100–131 triệu/m² (2025–26) · Tăng: ~3–4× trong một thập kỷ · Động lực: Metro số 1 vận hành

Masteri Thảo Điền — dự án đưa tên tuổi Masterise lên bản đồ. Mở bán 2014 ở mức ~35 triệu/m², thứ cấp 2025–26 đạt ~100–131 triệu/m² (Nhà Tốt) — tăng ~3–4 lần một thập kỷ, cộng hưởng Metro số 1.

★ Talking point: "Masteri Thảo Điền 35 triệu năm 2014, nay hơn 100 triệu/m². Đó là track record tăng giá thực của thương hiệu Masteri ngay tại TP.HCM."'),
  ('ad546e1b-2f82-59ca-984b-75d5515e124f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Grand Marina Saigon','brand','Marriott & JW Marriott · Q1

Vị trí: Ba Son, Quận 1 — 10 ha · Thương hiệu: Marriott & JW Marriott lớn nhất thế giới · Mốc: Marriott Lake tower khai trương 14/11/2023

Grand Marina Saigon — khu căn hộ hàng hiệu Marriott & JW Marriott lớn nhất thế giới, 10 ha tại Ba Son Q1. JW Marriott Residences Sea tower (2/2025) là khu hàng hiệu JW Marriott đô thị đầu tiên châu Á – TBD.

★ Talking point: "Grand Marina là đỉnh tháp thương hiệu Masterise. Cosmo Central thừa hưởng cùng tiêu chuẩn thi công và vận hành."'),
  ('e7c905de-8605-573d-b8b5-9d078849ba0c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','The Grand Hanoi','brand','Ritz-Carlton Residences

Vị trí: 22–24 Hàng Bài, Hà Nội · Thương hiệu: Ritz-Carlton thứ 5 châu Á – TBD

The Grand Hanoi — The Ritz-Carlton Residences thứ 5 tại châu Á – Thái Bình Dương, vị trí kim cương Hàng Bài, khai trương 5/2024.'),
  ('ed4b6564-c77d-596f-9e07-512d3dba7416','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','The Rivus by Elie Saab','brand','121 dinh thự Elie Saab

Quy mô: 121 dinh thự — duy nhất VN · Thương hiệu: Elie Saab (Haute Couture) · Giải: Best Residential Design in Asia 2025 (AADA)

The Rivus — 121 dinh thự hàng hiệu Elie Saab độc nhất Việt Nam (chỉ ~500 căn toàn cầu), trong Vinhomes Grand Park. Đạt giải "Best Residential Design in Asia 2025".'),
  ('15cd78db-de64-5b19-a2bd-a2e0b9b245bb','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Foster + Partners','partner','Quy hoạch tổng thể TGC

Vai trò: Cố vấn kiến trúc & quy hoạch tổng thể TGC · Ký kết: 22/02/2022, London · Công trình: Apple HQ · Sân bay Hong Kong · Bloomberg HQ · Sáng lập: Norman Foster (Pritzker Prize)

Foster + Partners — studio kiến trúc huyền thoại đứng sau Apple Park, sân bay quốc tế Hong Kong, Bloomberg HQ London, tòa Gherkin, sân Wembley, Lusail Stadium. Norman Foster đoạt giải Pritzker. F+P được bổ nhiệm làm cố vấn kiến trúc & quy hoạch tổng thể The Global City (22/02/2022) — township đầu tiên của F+P tại Việt Nam, đồng thời định hướng kiến trúc Cosmo Central.

★ Talking point: "The Global City là khu đô thị DUY NHẤT tại TP.HCM do Foster + Partners — studio thiết kế Apple Park và sân bay Hong Kong — quy hoạch. Không có đối thủ nào có pedigree này."'),
  ('c0ef2956-cace-5e18-af36-de97977e9469','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','WATG','partner','Cảnh quan TGC

Vai trò: Quy hoạch cảnh quan TGC · Vị thế: Top 3 hãng thiết kế hospitality thế giới

WATG — một trong những hãng thiết kế hospitality lớn nhất thế giới (top 3 BD+C Giants 400 2025), phụ trách cảnh quan The Global City: bố trí không gian, ánh sáng, gió, 450.000 m² cây xanh & mặt nước.

★ Talking point: "450.000 m² cây xanh và mặt nước được quy hoạch bởi WATG — triết lý đối thoại với thiên nhiên ngay giữa lõi đô thị."'),
  ('54485e33-e6fa-5955-bfa6-c291d9d53581','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Marriott International','partner','Hợp tác: Grand Marina (Marriott, JW Marriott)

Tập đoàn khách sạn hàng đầu thế giới — đối tác thương hiệu của Masterise tại Grand Marina Saigon (Marriott & JW Marriott Residences).'),
  ('c7f367e6-2f45-56a3-a4ed-db758c1e5e6c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','The Ritz-Carlton','partner','Hợp tác: The Grand Hanoi

Thương hiệu khách sạn siêu sang — The Ritz-Carlton Residences tại The Grand Hanoi (thứ 5 châu Á – TBD).'),
  ('6ed156ea-d2f5-5dee-89c1-92a70039f163','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Elie Saab','partner','Hợp tác: The Rivus — 121 dinh thự

Nhà mốt Haute Couture Lebanon — lần đầu thiết kế dinh thự hàng hiệu tại Việt Nam qua The Rivus.'),
  ('d3220ba5-7f03-5271-ac23-16969b080b07','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','The Global City','masterplan','117.4 ha · Foster + Partners

Quy mô: 117.4 ha · Chủ đầu tư: Masterise Homes · Quy hoạch: Foster + Partners (22/02/2022) · Cảnh quan: WATG — 450,000 m² xanh & mặt nước · Vị trí: Đỗ Xuân Hợp, P. Bình Trưng, TP.HCM · Định vị: Biểu tượng trung tâm chuẩn sống toàn cầu

The Global City — khu đô thị phức hợp 117.4 ha do Masterise Homes phát triển, là khu đô thị duy nhất tại TP.HCM được Foster + Partners quy hoạch tổng thể. Mô hình all-in-one quốc tế: TTTM 123,000 m², 6 trường quốc tế, 1 bệnh viện quốc tế, kênh đào nhạc nước lớn nhất Đông Nam Á (2km), SOHO, City Park, Speedway. Định vị "Biểu tượng trung tâm chuẩn sống toàn cầu" — New Downtown phía Đông, giữa Thủ Thiêm IFC và sân bay Long Thành.

★ Talking point: "The Global City không phải dự án — là một thành phố thu nhỏ chuẩn quốc tế 117 ha. Cosmo Central nằm ngay trái tim của thành phố đó."'),
  ('fca6ecd9-5453-5254-b0cc-cd9bb2421d13','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Kênh đào nhạc nước','masterplan','Lớn nhất Đông Nam Á · 2km

Chiều dài: ~2 km · Vị thế: Kênh nhạc nước al-fresco lớn nhất ĐNÁ

Kênh đào nhạc nước dài hơn 2km — lớn nhất Đông Nam Á, chạy xuyên The Global City. Cosmo Central có view trực tiếp ra kênh, với bến kayak nội khu.

★ Talking point: "Căn hộ view kênh nhạc nước lớn nhất Đông Nam Á — đây là loại view không thể sao chép ở bất kỳ dự án nào khác TP.HCM."'),
  ('32636c4e-7017-5ed9-8a3e-58241a3b03a3','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','TTTM 123,000 m²','masterplan','Grade-A shopping mall

Quy mô: ~123,000 m² (một số tài liệu 125,000) · Hạng: Grade-A, thuộc nhóm lớn nhất VN

Trung tâm thương mại Grade-A ~123,000 m² — thuộc nhóm lớn nhất Việt Nam, đi bộ 5 phút từ Cosmo Central.'),
  ('e5852e72-7a6f-56dd-a2ef-5ef900fa3091','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Khu SOHO','masterplan','Phố thương mại sôi động

Loại: Shophouse thấp tầng · Vị trí: Liền kề Cosmo Central

Khu phố thương mại SOHO — shophouse thấp tầng sôi động, đi bộ 1 phút từ Cosmo Central, tạo nhịp sống thương mại ngay dưới chân tháp.'),
  ('aede14ad-6087-56c9-9f53-baa74d1cae80','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','6 trường QT + BV QT','masterplan','All-in-one

Giáo dục: 6 trường tiêu chuẩn quốc tế · Y tế: 1 bệnh viện tiêu chuẩn quốc tế

The Global City quy hoạch 6 trường học quốc tế + 1 bệnh viện quốc tế nội khu — đáp ứng nhu cầu giáo dục, y tế trong bán kính đi bộ, đúng tiêu chí top khách hàng ưu tiên (giáo dục 33%, y tế 32%).

★ Talking point: "Trường quốc tế và bệnh viện quốc tế ngay trong khu đô thị — con đi học, ông bà khám bệnh đều trong bán kính đi bộ. Đó là all-in-one thật sự."'),
  ('a1258df7-5adc-5c26-8b95-e19449c0d78b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masteri Park Place','cluster','CT5 · The Global City

Vị trí: CT5, ôm 2 mặt nước · Định vị: Giao điểm năng lượng

Phân khu cao tầng tại CT5 The Global City — "giao điểm năng lượng" ôm trọn 2 mặt nước. Cùng hệ sinh thái với Cosmo Central.'),
  ('e1037914-1ce0-5576-aae8-3b61b603e99b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Masteri Grand View','cluster','Mặt tiền kim cương

Định vị: Flexi-luxury, modernista · Giá tham khảo: ~120–130 triệu/m² (môi giới)

Phân khu cao tầng đầu tiên tại vị trí "kim cương" mặt tiền The Global City. Giá môi giới tham khảo ~120–130 triệu/m².'),
  ('e09ba101-7d71-5b48-bfcf-d84b0136b9d8','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','LUMIÈRE Midtown','cluster','The Art of Living

Dòng: LUMIÈRE Series tại TGC · Giá tham khảo: ~150–160 triệu/m² (môi giới)

Biểu tượng dòng LUMIÈRE tại The Global City — kiến trúc New York hiện đại. Giá môi giới tham khảo ~150–160 triệu/m².'),
  ('c8d0354c-a0c6-5eae-985e-c788aa4a525a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','SOLA Villas','cluster','Dinh thự biểu tượng

Loại: Biệt thự/dinh thự · Giá đất tham khảo: ~380–570 triệu/m² (môi giới)

Dòng dinh thự biểu tượng tại The Global City. Giá đất môi giới tham khảo ~380–570 triệu/m² — cho thấy mặt bằng giá thấp tầng trong khu đã rất cao.'),
  ('96c486f9-87a9-5b54-a990-84f5206a409f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','KLH TDTT Rạch Chiếc','cluster','Sun Group · 186.78 ha

Quy mô: 186.78 ha · Vốn: ~VND 145,629 tỷ (~6 tỷ USD) · Sân vận động: 65,000–75,000 chỗ · Khởi công: 15/01/2026 · Tầm nhìn: 2030 — biểu tượng quốc gia

Khu liên hợp TDTT Quốc gia Rạch Chiếc (Sun Group) — 186.78 ha, ~VND 145,629 tỷ, sân vận động 65,000–75,000 chỗ, nhà thi đấu 18,000 chỗ, trung tâm thể thao dưới nước, bệnh viện thể thao. Khởi công 15/01/2026. Cùng Saigon Sports City (64 ha) và The Global City (117.4 ha) tạo thành cụm đô thị – thể thao ~368 ha duy nhất TP.HCM, kết nối trực tiếp qua đường Liên Phường.

★ Talking point: "Cosmo Central nằm trong cụm đô thị – thể thao 368 ha duy nhất TP.HCM: The Global City + Saigon Sports City + Rạch Chiếc. Cư dân có cả sân vận động quốc gia trong tầm tay."'),
  ('1463d5e0-3a04-5441-a817-12655c62c7d3','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Saigon Sports City','cluster','64 ha · cụm thể thao

Quy mô: 64 ha · Ghi chú: Keppel đã bán 70% (2025), giữ 30%

Saigon Sports City 64 ha — mắt xích giữa Rạch Chiếc và The Global City trong cụm đô thị – thể thao 368 ha. Keppel đã chuyển nhượng 70% vốn (2025), giữ 30% làm căn hộ sau này.'),
  ('b86c76db-5456-5748-8eec-281469b3f973','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Concert ATVCG','event','Anh Trai Vượt Ngàn Chông Gai

Thời gian: Chặng cuối 6–7/9/2025 · Quy mô: 20.000 → hơn 50.000 người/đêm

Chuỗi concert "Anh Trai Vượt Ngàn Chông Gai" — chặng cuối 6–7/9/2025 tại The Global City, thu hút từ 20.000 lên hơn 50.000 người/đêm (Nhân Dân, VnExpress).

★ Talking point: "50.000 người đổ về The Global City trong một đêm concert. Đó là sức hút khu đô thị mà tiền không mua được — và cư dân Cosmo Central sống ngay tại đó."'),
  ('8ab78428-a7de-5312-b886-b85595dd9e98','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','SOOBIN Concert','event','29/11/2025 · sold-out

Thời gian: 29/11/2025 · Tên: All-Rounder The Final

Live Concert SOOBIN "All-Rounder The Final" — 29/11/2025 tại The Global City, cháy vé (Báo Xây Dựng).'),
  ('1d902bc9-2008-5cf3-a109-aa7a98cd5a7d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Quốc Thiên SKYNote','event','22/11/2025 · ~10,000 người

Thời gian: 22/11/2025 · Tên: SKYNote 2025: The Reflection

Concert Quốc Thiên "SKYNote 2025" — 22/11/2025 tại The Global City, gần 10.000 khán giả (TTXVN/Thể thao Văn hóa).'),
  ('d7a82721-0a3f-5bda-94bc-a0f7017de6be','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','PPA Tour Asia','event','MB Vietnam Open 2025

Môn: Pickleball quốc tế · Địa điểm: TGC Sports Complex / Arena

PPA Tour Asia — MB Vietnam Open 2025 diễn ra tại The Global City Sports Complex — giải pickleball chuyên nghiệp quốc tế, định vị khu đô thị trên bản đồ thể thao khu vực.'),
  ('17ca43cb-1098-55ae-8793-86286c2643ea','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Pink Run / Nón Hồng','event','25/10/2025 · 5,000+ runner

Thời gian: 25/10/2025 · Quy mô: >5,000 runner

Vietnam Women Run / Ngày hội Nón Hồng — 25/10/2025 tại The Global City, hơn 5.000 vận động viên (Người Lao Động).'),
  ('8ae11e78-e2be-5746-810c-fd8d76abe3c4','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Global Wishmas 2025','event','12/2025 · lễ hội Giáng sinh

Thời gian: 20, 21, 24/12/2025 · Loại: Chợ Giáng sinh châu Âu + diễu hành

Global Wishmas 2025 — chợ Giáng sinh phong cách châu Âu, diễu hành Wishmas, dàn nhạc giao hưởng, thuộc chuỗi Global Festive (13/12/2025 – 10/1/2026).'),
  ('d82dcb0c-6633-5928-80bc-2d4442b694ac','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Daddy Cool Diner','event','Quán retro thường trực · City Park

Loại: Diner retro Mỹ thập niên 90 · Mở cửa: Tết 2026 · ~1,000+ khách/ngày

Daddy Cool — diner phong cách Mỹ retro thập niên 90 thường trực tại City Park (mở Tết 2026), thu hút ~1.000+ khách/ngày. Điểm đến hằng ngày chứ không chỉ sự kiện.'),
  ('e39eede8-8f14-53a1-9389-91752c72dee7','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Đường Liên Phường','infra','Thông xe 8/11/2025

Chiều dài: ~6.7 km · Đoạn TGC: 1.6 km, lộ giới 60m, 6 làn · Kết nối: Cát Lái – Mai Chí Thọ → Vành đai 3 · Mốc: Thông toàn tuyến kỹ thuật 8/11/2025

Đường Liên Phường (~6.7 km) nối Cát Lái – Mai Chí Thọ xuyên qua trái tim The Global City đến Vành đai 3. Đoạn kết nối TGC – Mai Chí Thọ dài 1.6 km, lộ giới 60m, 6 làn. Thông toàn tuyến kỹ thuật 8/11/2025 (cầu vượt rạch Mương Kinh). Rút Thảo Điền → TGC còn ~5 phút; Thủ Thiêm/Q1 → TGC ~10–15 phút; kết nối thẳng cụm thể thao Rạch Chiếc.

★ Talking point: "Đường Liên Phường — chính Masterise tham gia làm — đã thông xe tháng 11/2025, đưa Thảo Điền về The Global City chỉ còn 5 phút. Hạ tầng không còn là lời hứa, nó đã chạy."'),
  ('67454760-4a0f-5734-a133-2802d720d039','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Nút giao An Phú','infra','Hoàn thành Q2/2026

Quy mô: Nút giao 3 tầng — VND 3,408 tỷ · HC1-01: Thông xe 30/6/2025 · Cầu N2: Thông xe 31/12/2025 · HC1-02: Thông xe 2/2/2026 · Hoàn thành: Q2/2026

Nút giao An Phú — nút giao 3 tầng VND 3,408 tỷ, cửa ngõ biểu tượng mới phía Đông. HC1-01 (30/6/2025), cầu N2 (31/12/2025), HC1-02 (2/2/2026) đã thông; hoàn thành toàn bộ Q2/2026. Tổ hợp N2 + HC1-02 giảm ~80% ùn tắc tại nút.

★ Talking point: "Khi nút giao An Phú hoàn thành Q2/2026, Cosmo Central kết nối thẳng cao tốc Long Thành và trung tâm Q1 — đúng lúc dự án vào giai đoạn tăng tốc thi công."'),
  ('848ed61e-802f-5ada-955a-ec40a9d99b76','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Vành đai 2','infra','Lá chắn trục trung tâm · 2027

Đoạn 1+2+3: Cầu Phú Hữu → Gò Dưa, ~9km · Khởi công: 19/12/2025 · Hoàn thành: 2027

Vành đai 2 — đoạn 1+2+3 (cầu Phú Hữu → Võ Nguyên Giáp → Phạm Văn Đồng → Gò Dưa, ~9km) khởi công 19/12/2025, hoàn thành 2027. "Lá chắn trục trung tâm" — chuyển hướng xe lớn khỏi trục Đỗ Xuân Hợp / Mai Chí Thọ.

★ Talking point: "Vành đai 2 khép kín 2027 đẩy xe tải ra khỏi trục trung tâm — chất lượng sống quanh Cosmo Central được nâng lên rõ rệt."'),
  ('b2fa26a2-36bf-5d52-bbde-988aea043798','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Vành đai 3','infra','Đòn bẩy kinh tế · 6/2026

Tổng: 76.34 km, ~VND 75,378 tỷ · Đoạn Đông 14.7km: Thông kỹ thuật 19/12/2025 · Toàn tuyến: Vận hành 30/6/2026 · Kết nối: HCM · Đồng Nai · Tây Ninh · BR-VT

Vành đai 3 — 76.34 km, ~VND 75,378 tỷ. Đoạn Đông 14.7km cầu cạn qua Thủ Đức thông kỹ thuật 19/12/2025; toàn tuyến vận hành 30/6/2026. Đòn bẩy kinh tế liên vùng, kết nối cao tốc Long Thành.

★ Talking point: "Vành đai 3 vận hành 6/2026 — chỉ vài tháng trước khi Cosmo Central tăng tốc. Cả vùng Đông được tái định giá theo trục kinh tế mới này."'),
  ('c0009f40-a3e8-552a-bde6-0ff8282be270','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Mở rộng cao tốc Long Thành','infra','8–10 làn · 12/2026

Quy mô: Mở rộng 8–10 làn xe · Khởi công: 19/8/2025 · Hoàn thành: Dec 2026 (đồng bộ sân bay Long Thành)

Mở rộng cao tốc TP.HCM – Long Thành – Dầu Giây lên 8–10 làn (VEC), khởi công 19/8/2025, cơ bản hoàn thành Dec 2026 — đồng bộ với sân bay Long Thành. Cầu Long Thành đơn nguyên mới hợp long 12/2026.

★ Talking point: "Cao tốc mở rộng xong cuối 2026 — Cosmo Central tới sân bay Long Thành chỉ còn ~30 phút. Đó là khoảng cách của một đô thị sân bay đẳng cấp."'),
  ('f62261d6-c8a6-5f84-b001-eead6bd67bc6','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Metro 2 — Tham Lương','infra','Khởi công 15/01/2026

Tuyến: Bến Thành – Tham Lương · Quy mô: 11.3 km, 11 ga, VND 55,179 tỷ · Vận hành: Q4/2030

Metro số 2 (Bến Thành – Tham Lương) — 11.3 km, 11 ga, khởi công 15/01/2026, vận hành Q4/2030. Trục xương sống kết nối trung tâm.'),
  ('971d28a8-1ca5-5004-9d22-58a140f4e26b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Metro 2 — Thủ Thiêm','infra','Khởi công 29/4/2026

Tuyến: Bến Thành – Thủ Thiêm · Quy mô: 6 km, 6 ga ngầm dưới sông Sài Gòn · Vận hành: Q3/2030

Metro số 2 nhánh Bến Thành – Thủ Thiêm — 6 km, 6 ga ngầm (hầm metro đầu tiên xuyên đáy sông Sài Gòn), khởi công 29/4/2026, vận hành Q3/2030. Kết nối thẳng trục Long Thành.

★ Talking point: "Trục Tham Lương – Bến Thành – Thủ Thiêm – Long Thành trở thành xương sống metro. Cosmo Central tiếp cận qua Ga Thủ Thiêm chỉ 10 phút đi đường Liên Phường."'),
  ('091d9d33-19bf-5c39-9246-a84dcf5164e6','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ĐSĐT Thủ Thiêm – Long Thành','infra','Khởi công trước 30/6/2026

Chiều dài: 48 km, ~VND 84,000 tỷ · Kết nối: Ga Thủ Thiêm → sân bay Long Thành 30 phút · Vận hành: 2030

Đường sắt đô thị Thủ Thiêm – Long Thành (48 km, ~VND 84,000 tỷ) — khởi công trước 30/6/2026, vận hành 2030. Kết nối The Global City (qua Ga Thủ Thiêm) đến sân bay Long Thành trong 30 phút.'),
  ('cc48c271-5b68-55bd-98a0-db5084ffe518','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Sân bay Long Thành','infra','Khai thác giữa 2026

Giai đoạn 1: 25 triệu khách/năm, ~US$16 tỷ · Bay thử Boeing 787: 15/12/2025 · Chuyến TM đầu: 19/12/2025 · Khai thác TM: Giữa 2026

Sân bay quốc tế Long Thành — giai đoạn 1 đón 25 triệu khách/năm, ~US$16 tỷ. Bay thử Boeing 787 ngày 15/12/2025, 3 chuyến thương mại đầu 19/12/2025, khai thác thương mại giữa 2026.

★ Talking point: "Sân bay Long Thành khai thác giữa 2026 kéo theo hàng vạn chuyên gia về phía Đông. The Global City là điểm dừng chân chuẩn quốc tế gần nhất giữa Thủ Thiêm và Long Thành."'),
  ('f0e122ef-2006-5380-a617-cd45a8157665','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Trung tâm Tài chính QT','finance','Công bố 21/12/2025

Công bố: 21/12/2025 (NĐ 323/2025/NĐ-CP) · Quy mô HCM: ~898 ha · Mô hình: Một trung tâm – hai địa điểm · Lộ trình: 2026 hạ tầng → 2030 ASEAN → 2035 toàn cầu

Trung tâm Tài chính Quốc tế (IFC) — Thủ tướng công bố thành lập 21/12/2025. Cấu phần TP.HCM ~898 ha trải dài Phường Sài Gòn, Phường Bến Thành và Thủ Thiêm. Lộ trình: 2026 hạ tầng & thu hút đầu tư → 2027–2030 tầm vóc ASEAN (trụ sở dời về Thủ Thiêm) → 2035 tầm vóc toàn cầu. IFC sẽ kéo dòng vốn và chuyên gia nước ngoài về Thủ Thiêm — nhu cầu nhà ở cao cấp lân cận tăng mạnh. Cosmo Central cách Thủ Thiêm ~10 phút.

★ Talking point: "Trung tâm Tài chính Quốc tế đặt tại Thủ Thiêm — New Downtown của TP.HCM. Cosmo Central cách đó 10 phút, là điểm an cư cho chính các chuyên gia tài chính sẽ về đây."'),
  ('be8e927b-b5e2-5cf9-921d-cc99b0c98a04','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Thủ Thiêm CBD','finance','New Downtown

Vai trò: CBD tài chính mới · Giá biệt thự Sala: 900 triệu – 1.5 tỷ/m² (môi giới)

Thủ Thiêm — trung tâm tài chính mới của TP.HCM, nơi đặt lõi IFC. Giá biệt thự Sala đã đạt 900 triệu – 1.5 tỷ/m² (môi giới), tạo mặt bằng giá tham chiếu cho toàn khu Đông.

★ Talking point: "Thủ Thiêm đã chạm ngưỡng tỷ đồng/m². Cosmo Central — cách 10 phút, giá căn hộ — đang ở vùng định giá hấp dẫn hơn nhiều so với mặt bằng CBD mới."'),
  ('4a6791a9-3101-5527-b17d-d5f781a1e46f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Thị trường căn hộ 2026','finance','Savills / CBRE

Hấp thụ 2025: 82% — cao nhất 5 năm · Giá sơ cấp HCM: ~92–102 triệu/m² · Cao cấp >110tr/m²: 56% nguồn cung mới · Pipeline khu Đông: ~50% giai đoạn 2026–28 · Dự báo giá: +10–20%/năm

Theo Savills/CBRE: 2025 TP.HCM hấp thụ ~11.500 căn, tỷ lệ 82% (cao nhất 5 năm); giá sơ cấp ~92–102 triệu/m²; phân khúc >110 triệu/m² chiếm 56% nguồn cung mới; sản phẩm dưới 50 triệu/m² còn 12%. Pipeline 2026–28 ~58.000 căn, khu Đông chiếm ~50%. Dự báo giá sơ cấp +10–20%/năm.

★ Talking point: "Phân khúc bình dân đang biến mất khỏi trung tâm — quỹ đất cực hiếm. Mua căn hộ cao cấp khu Đông hôm nay là đón đầu mặt bằng giá mới tăng 10–20%/năm."'),
  ('2ccab86d-aff9-50bb-8c94-ffd5a4a27f36','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','Vĩ mô Việt Nam 2025–26','finance','GSO

GDP Q1/2025: +6.93% (cao nhất từ 2020) · FDI giải ngân 2025: US$27.62 tỷ (+9%, cao nhất 5 năm) · GRDP HCM 2025: +7.53% · Dòng tiền: BĐS là kênh trú ẩn dài hạn

Theo Tổng cục Thống kê (GSO): GDP Q1/2025 +6.93% (cao nhất từ 2020); FDI giải ngân cả năm 2025 đạt US$27.62 tỷ (+9% YoY, cao nhất 5 năm); GRDP TP.HCM 2025 +7.53%. Lãi suất hạ nhiệt cuối 2025 đẩy dòng tiền về BĐS — kênh đầu tư phát triển bền vững, dài hạn.

★ Talking point: "Chứng khoán và vàng biến động, lãi suất hạ — dòng tiền tìm về BĐS chuẩn quốc tế. Đó là lý do căn hộ cao cấp khu Đông đang hút vốn mạnh nhất."');

insert into map_edges (id, org_id, project_id, source_id, target_id, kind) values
  ('eb40cb7c-ba82-5b70-9ef5-6566292e0020','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','e6f4d1de-9eff-5fd4-8006-5ce6c392b885','part_of'),
  ('f6f91674-39cb-54d8-8f35-5d04b8fa6802','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','25d7515c-d8d0-5a8e-9460-d12e28db1347','part_of'),
  ('81e6c1d5-9e18-5830-9992-a2d1a270abcc','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','5a098ea5-5037-59e7-8581-133ec4abdd4e','part_of'),
  ('8c4bb893-21c3-5498-966d-0435106733c0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','0a05e557-daa5-5014-9ffb-8d14ae3ee4a5','supports'),
  ('22a3f6da-5e1e-5eca-8f94-ebba9541e195','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','96a36515-accc-5a3d-ab8c-10295f8a134e','relates'),
  ('ca295b95-638d-5a2d-b6cb-b958729125d9','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','b3118f66-71cd-5a63-9105-5a97cdbf493c','supports'),
  ('bff39aaa-0120-5dac-9529-2e1cb894c007','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','d789b26b-cd06-5620-a387-ba98aa3c4107','part_of'),
  ('aae436f5-0d97-5e2b-8a62-d121d41acb03','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','d3220ba5-7f03-5271-ac23-16969b080b07','part_of'),
  ('19f5d0fd-1d94-594c-a23d-21c9ca2353f0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','15cd78db-de64-5b19-a2bd-a2e0b9b245bb','part_of'),
  ('153b8333-5295-5bf8-bb70-899413d499fa','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b3118f66-71cd-5a63-9105-5a97cdbf493c','a7f489a9-22cb-5766-a5b2-c9056e48579c','part_of'),
  ('050352cf-0ff7-5b95-bf70-bdd0251a5058','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','a7f489a9-22cb-5766-a5b2-c9056e48579c','882a47f5-3631-55b8-9b0c-4dd6539132d8','supports'),
  ('57368bdd-950b-5654-8c38-65b843faa6c0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','a7f489a9-22cb-5766-a5b2-c9056e48579c','5efd62f3-2209-50ad-baac-f29bd057fc34','supports'),
  ('742fd5db-9058-5fdb-a7ac-6c55331e04da','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','a7f489a9-22cb-5766-a5b2-c9056e48579c','379ba9ad-fda6-5063-84b3-5b090650faa3','supports'),
  ('1c9378a6-d449-576b-84df-ad1a01b28953','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','a7f489a9-22cb-5766-a5b2-c9056e48579c','71536758-a0c3-5c7c-b748-ca4af52b3b74','supports'),
  ('23bc525b-d925-585b-aa47-dbda0798feb0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','a7f489a9-22cb-5766-a5b2-c9056e48579c','e41c9ed7-ed76-59cc-9a09-96b77b269183','supports'),
  ('0a5dd7c6-d456-5de2-a05f-eac13d52c164','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','a7f489a9-22cb-5766-a5b2-c9056e48579c','faa80c96-4365-59a1-9897-d1dc5a7e98c4','supports'),
  ('4fd3012f-e2be-58e0-972b-bba82494a3a3','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','379ba9ad-fda6-5063-84b3-5b090650faa3','supports'),
  ('18090daf-e97d-5146-96fb-af9f6f84dc36','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','5efd62f3-2209-50ad-baac-f29bd057fc34','supports'),
  ('accaab05-2e5f-5235-a393-cc4023ae8313','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b3118f66-71cd-5a63-9105-5a97cdbf493c','d789b26b-cd06-5620-a387-ba98aa3c4107','part_of'),
  ('dfe34f9a-cdf5-5063-a72b-c99c2efd4e5a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b3118f66-71cd-5a63-9105-5a97cdbf493c','bd8209bb-d2d6-50f3-92a0-0dce42a1b578','part_of'),
  ('d517ebd3-11ce-5881-b004-20e0d7bdb514','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b3118f66-71cd-5a63-9105-5a97cdbf493c','22567a09-5af3-57d0-be5a-2123df44d8be','part_of'),
  ('421282e7-df9b-5187-89f7-946404122ef0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b3118f66-71cd-5a63-9105-5a97cdbf493c','bbff31a8-7c0d-53b3-ab6a-4213c9e382af','relates'),
  ('4a7e672e-b962-538a-919a-dc45a3cb3fd5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','22567a09-5af3-57d0-be5a-2123df44d8be','ad546e1b-2f82-59ca-984b-75d5515e124f','part_of'),
  ('0c8ef075-c8d7-5a42-851d-eed875e3795c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','22567a09-5af3-57d0-be5a-2123df44d8be','e7c905de-8605-573d-b8b5-9d078849ba0c','part_of'),
  ('dae9104c-2736-55f1-ac54-f287c6755a60','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','22567a09-5af3-57d0-be5a-2123df44d8be','ed4b6564-c77d-596f-9e07-512d3dba7416','part_of'),
  ('043e4f8d-8b22-5bb5-9b9e-f9d505d7fd9d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d789b26b-cd06-5620-a387-ba98aa3c4107','bbff31a8-7c0d-53b3-ab6a-4213c9e382af','supports'),
  ('9dfe60cc-c807-55ef-aa7a-3d046f70d666','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b3118f66-71cd-5a63-9105-5a97cdbf493c','15cd78db-de64-5b19-a2bd-a2e0b9b245bb','supports'),
  ('7e65a16f-f147-5394-8022-92c5dd0b45cb','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b3118f66-71cd-5a63-9105-5a97cdbf493c','c0ef2956-cace-5e18-af36-de97977e9469','supports'),
  ('2f7b40ec-5706-551c-aa27-87d5eb3d49f1','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ad546e1b-2f82-59ca-984b-75d5515e124f','54485e33-e6fa-5955-bfa6-c291d9d53581','part_of'),
  ('80287c87-b515-5a2a-979b-86f9292cd556','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','e7c905de-8605-573d-b8b5-9d078849ba0c','c7f367e6-2f45-56a3-a4ed-db758c1e5e6c','part_of'),
  ('2241cb74-b510-50a1-b49a-0a2501b4e683','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ed4b6564-c77d-596f-9e07-512d3dba7416','6ed156ea-d2f5-5dee-89c1-92a70039f163','part_of'),
  ('26d498dd-f903-5f9e-ba0b-4a8c193f6e41','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','15cd78db-de64-5b19-a2bd-a2e0b9b245bb','part_of'),
  ('35f33255-4100-5fcb-9760-fec2ce1762ce','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','c0ef2956-cace-5e18-af36-de97977e9469','part_of'),
  ('28c99c07-d8be-53c6-bae6-aff65cc06759','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','fca6ecd9-5453-5254-b0cc-cd9bb2421d13','part_of'),
  ('1fd8300e-0e80-5120-a6d2-ad6e4adfa2b3','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','32636c4e-7017-5ed9-8a3e-58241a3b03a3','part_of'),
  ('5209626f-3cbc-5fc3-ad2c-769c60be363e','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','e5852e72-7a6f-56dd-a2ef-5ef900fa3091','part_of'),
  ('0003960c-338a-5944-9396-e5b9e964498a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','aede14ad-6087-56c9-9f53-baa74d1cae80','part_of'),
  ('1f530435-56b2-5f2e-9a2d-be1b243f956b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','fca6ecd9-5453-5254-b0cc-cd9bb2421d13','near'),
  ('49e76541-a41e-52fa-96b9-25d2404dbf0c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','e5852e72-7a6f-56dd-a2ef-5ef900fa3091','near'),
  ('708394a2-03f2-56e3-bbc4-5f25cbeee24c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','a1258df7-5adc-5c26-8b95-e19449c0d78b','part_of'),
  ('907f4657-f72f-5afd-9569-d13dbf6c8770','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','e1037914-1ce0-5576-aae8-3b61b603e99b','part_of'),
  ('4b4de185-c936-57b7-97f5-a1f181c0caa2','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','e09ba101-7d71-5b48-bfcf-d84b0136b9d8','part_of'),
  ('409b5e29-4ad1-5eb5-b818-a4bb98ed5f8d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','c8d0354c-a0c6-5eae-985e-c788aa4a525a','part_of'),
  ('0b73b11a-0d9d-5e53-a575-81de296ac997','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','e09ba101-7d71-5b48-bfcf-d84b0136b9d8','bd8209bb-d2d6-50f3-92a0-0dce42a1b578','part_of'),
  ('5be02232-4b12-58f9-aeae-d24d481aae00','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','a1258df7-5adc-5c26-8b95-e19449c0d78b','d789b26b-cd06-5620-a387-ba98aa3c4107','part_of'),
  ('e19a6072-d46f-54c8-b534-8878e489420e','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','e1037914-1ce0-5576-aae8-3b61b603e99b','d789b26b-cd06-5620-a387-ba98aa3c4107','part_of'),
  ('daddc26e-3808-59bb-b263-021582d652e5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','1463d5e0-3a04-5441-a817-12655c62c7d3','part_of'),
  ('55ee6863-778d-531d-a859-ae135538aa84','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','1463d5e0-3a04-5441-a817-12655c62c7d3','96c486f9-87a9-5b54-a990-84f5206a409f','part_of'),
  ('42192b6e-832f-57e6-b5a3-2192e796cb3a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','96c486f9-87a9-5b54-a990-84f5206a409f','e39eede8-8f14-53a1-9389-91752c72dee7','near'),
  ('40821505-a393-5202-b542-beba3823b23c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','b86c76db-5456-5748-8eec-281469b3f973','relates'),
  ('624823b4-5017-5646-979e-a157eadf5cfd','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','8ab78428-a7de-5312-b886-b85595dd9e98','relates'),
  ('79ca6ef4-8731-5bed-a5c2-e5be0d679d90','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','1d902bc9-2008-5cf3-a109-aa7a98cd5a7d','relates'),
  ('96533943-0548-5aae-8ce3-2aa47312c975','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','d7a82721-0a3f-5bda-94bc-a0f7017de6be','relates'),
  ('594526c6-bd92-55e4-8a58-2ad4b72c1c92','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','17ca43cb-1098-55ae-8793-86286c2643ea','relates'),
  ('2d92a99a-8364-526c-8eca-efc44a5d665d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','8ae11e78-e2be-5746-810c-fd8d76abe3c4','relates'),
  ('86884b1d-bc7f-5c17-b047-9a4008692d9a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','d82dcb0c-6633-5928-80bc-2d4442b694ac','near'),
  ('15d77662-635c-5dcd-ab4f-229b8f16a445','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','e39eede8-8f14-53a1-9389-91752c72dee7','part_of'),
  ('d3feb19c-6e01-5bd4-8543-5d9e9c5976c4','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','e39eede8-8f14-53a1-9389-91752c72dee7','near'),
  ('9a7face0-6bc8-5d55-b26c-fd2de9edcb41','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','e39eede8-8f14-53a1-9389-91752c72dee7','67454760-4a0f-5734-a133-2802d720d039','near'),
  ('825f1efb-72d5-5b80-a087-511bf6fb3a26','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','e39eede8-8f14-53a1-9389-91752c72dee7','b2fa26a2-36bf-5d52-bbde-988aea043798','near'),
  ('df948d01-cd8f-5854-b672-355957a63743','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','67454760-4a0f-5734-a133-2802d720d039','c0009f40-a3e8-552a-bde6-0ff8282be270','near'),
  ('006dba8f-9f8a-5bf8-9e87-f1696da1d61a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','c0009f40-a3e8-552a-bde6-0ff8282be270','cc48c271-5b68-55bd-98a0-db5084ffe518','near'),
  ('89b56a41-1ebb-5bcf-be5a-46ae52c6322c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','b2fa26a2-36bf-5d52-bbde-988aea043798','cc48c271-5b68-55bd-98a0-db5084ffe518','near'),
  ('9fa9b587-e260-521c-af26-ca86d6953db8','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','848ed61e-802f-5ada-955a-ec40a9d99b76','67454760-4a0f-5734-a133-2802d720d039','near'),
  ('457e9883-3e6c-5e89-81bc-b936ebc38efe','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','f62261d6-c8a6-5f84-b001-eead6bd67bc6','971d28a8-1ca5-5004-9d22-58a140f4e26b','near'),
  ('d2acb190-a830-58c4-a070-117710ac7a93','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','971d28a8-1ca5-5004-9d22-58a140f4e26b','091d9d33-19bf-5c39-9246-a84dcf5164e6','near'),
  ('ba1b9f00-da69-5857-8872-b8edf6b7a2a3','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','091d9d33-19bf-5c39-9246-a84dcf5164e6','cc48c271-5b68-55bd-98a0-db5084ffe518','near'),
  ('e6c89fdf-6bbb-546a-8043-d050d126a7a6','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','971d28a8-1ca5-5004-9d22-58a140f4e26b','be8e927b-b5e2-5cf9-921d-cc99b0c98a04','near'),
  ('aa0e7160-7ee8-5123-a649-0bd3f8c9fd63','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','67454760-4a0f-5734-a133-2802d720d039','supports'),
  ('8b563507-f90d-5fbf-884b-21c120cbf407','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','be8e927b-b5e2-5cf9-921d-cc99b0c98a04','f0e122ef-2006-5380-a617-cd45a8157665','supports'),
  ('162fc580-49fc-5aa7-b9a4-5b1a64db76ad','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','f0e122ef-2006-5380-a617-cd45a8157665','near'),
  ('10786923-847d-5174-b346-f37572591285','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','f0e122ef-2006-5380-a617-cd45a8157665','971d28a8-1ca5-5004-9d22-58a140f4e26b','near'),
  ('31bdede5-6dae-563a-9e0f-3fbd165f1f9b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','d3220ba5-7f03-5271-ac23-16969b080b07','be8e927b-b5e2-5cf9-921d-cc99b0c98a04','near'),
  ('9129e4f5-0409-5260-95c6-e8dabc38b566','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','ab118257-cbe5-5b47-bf43-2b47153184ae','4a6791a9-3101-5527-b17d-d5f781a1e46f','supports'),
  ('b908fe94-b008-54cf-8e66-9d0fe9b4a65b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','4a6791a9-3101-5527-b17d-d5f781a1e46f','2ccab86d-aff9-50bb-8c94-ffd5a4a27f36','supports'),
  ('ee83cdb9-11e4-5ebc-8413-ee7ec46cd798','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','f0e122ef-2006-5380-a617-cd45a8157665','2ccab86d-aff9-50bb-8c94-ffd5a4a27f36','supports'),
  ('86c5deaa-da0c-5c3f-8d46-40fba186e146','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a006','faa80c96-4365-59a1-9897-d1dc5a7e98c4','2ccab86d-aff9-50bb-8c94-ffd5a4a27f36','relates');
