-- Gladia knowledge map — generated by scripts/gen_gladia_map.mjs (do not edit by hand).
-- Rich per-project Obsidian map: developers, certifications, transit, comparables, policy.
-- Idempotent: clears this project's map then reinserts with deterministic UUIDv5 ids.

delete from map_edges where project_id = '00000000-0000-0000-0000-00000000a001';
delete from map_nodes where project_id = '00000000-0000-0000-0000-00000000a001';

insert into map_nodes (id, org_id, project_id, label, kind, note) values
  ('3dcde88f-fc3b-5011-9f09-f7d8960d0d46','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Gladia by the Waters','project','GLADIA HEIGHT

Diện tích: 11.8 ha · Tổng vốn: ~VND 10,200 tỷ (~S$600M) · Liên doanh: Keppel 49% × Khang Điền 51% · Vị trí: Võ Chí Công, Bình Trưng Đông, TP Thủ Đức · Sản phẩm: ~200 căn thấp tầng + ~600 căn cao tầng · Chứng nhận: BCA Green Mark for Districts (đầu tiên VN) · Trần: ~3.05m theo chuẩn Singapore · Mật độ XD: chỉ 23.3–38% (thấp hơn nhiều thị trường)

Gladia by the Waters là dự án hợp tác đầu tiên giữa Keppel (Singapore) và Khang Điền (Việt Nam) — vị trí 11.8 ha ba mặt giáp sông tại Bình Trưng Đông, TP Thủ Đức. Tổng giá trị phát triển ~VND 10,200 tỷ. Đây là dự án đầu tiên tại Việt Nam đạt chứng nhận BCA Green Mark for Districts từ Cục Xây dựng Singapore — vị thế độc nhất trên thị trường BĐS thấp tầng HCM, nơi 99% đối thủ chỉ có chứng nhận LOTUS Việt Nam hoặc không có chứng nhận nào. Sản phẩm đầu ra thị trường là thấp tầng, theo sau sẽ là phần cao tầng. Sản phẩm đầu tiên = nơi cả hai chủ đầu tư đặt cả uy tín thương hiệu.

★ Talking point: "Gladia không chỉ là một dự án — đây là lần đầu tiên Singapore và Việt Nam cùng cấp chứng nhận khu đô thị cho cùng một địa chỉ. Khi Anh/Chị mua Gladia, Anh/Chị đang mua một tiêu chuẩn quy hoạch toàn cầu."'),
  ('3dc3fc74-a162-5f0f-87a9-161954c8c052','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Keppel Land','developer','Vào Việt Nam: 1991 (>34 năm) · Dự án tại VN: 20+ dự án · Vốn đăng ký: US$3.5 tỷ+ · Nhân sự: 600+ (so với 8 năm 1991) · Pipeline: ~18,000 căn nhà

Keppel Land là cánh tay phát triển BĐS của Keppel Ltd. — vào Việt Nam từ 1991 ngay sau Đổi Mới, là nhà đầu tư BĐS nước ngoài đầu tiên tại Việt Nam. Track record: Saigon Centre, The Estella, Estella Heights, Empire City, Riviera Point, Palm City, Celesta. Tỷ lệ hấp thụ >99% tại Empire City và Riviera Point. Năm 2022 đạt 12 giải tại PropertyGuru Vietnam Property Awards bao gồm "Best Sustainable Real Estate Developer" và "Best Mixed-use Developer".

★ Talking point: "Keppel đã ở Việt Nam 34 năm — họ đã chứng kiến mọi chu kỳ thị trường. Họ không đến rồi đi như nhiều nhà đầu tư ngoại khác."'),
  ('58c1193c-245e-503c-b4d9-02d675092b21','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Keppel Ltd.','developer','Thành lập: 1968 (Keppel Shipyard, Singapore) · Vốn hóa: ~US$17.24 tỷ (4/2026) · Mã CK: SGX:BN4 · Cổ đông lớn nhất: Temasek 21.29% · Hoạt động: 20+ quốc gia

Keppel Ltd. là tập đoàn đa ngành Singapore, từ tên cũ "Keppel Corporation" đã chuyển sang mô hình asset-light theo Vision 2030. 4 mảng kinh doanh: Infrastructure (năng lượng, môi trường), Real Estate, Connectivity (data center, viễn thông), Corporate Activities. Top-10 công ty niêm yết tại Singapore. Cam kết net-zero 2050 đồng hành với cam kết COP26 của Việt Nam.

★ Talking point: "Cổ đông lớn nhất của Keppel là Temasek — công ty đầu tư của Chính phủ Singapore. Khi Anh/Chị mua Gladia, Anh/Chị có sự đảm bảo gián tiếp của Chính phủ Singapore."'),
  ('d5b6bff3-fa3a-512a-925e-d79d3b7588df','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Temasek Holdings','developer','Loại: Sovereign wealth fund · Sở hữu: Chính phủ Singapore · Cổ phần tại Keppel: 21.29% (3/2025)

Temasek là quỹ đầu tư quốc gia Singapore — sở hữu cổ phần đáng kể tại các tập đoàn lớn nhất Singapore bao gồm DBS, Singtel, Singapore Airlines, và Keppel. Sự hiện diện của Temasek tại Keppel mang lại kỷ luật tài chính, tiêu chuẩn quản trị toàn cầu và sự đảm bảo gián tiếp từ chính phủ Singapore.

★ Talking point: "Đây là điều khác biệt cốt lõi: Khi mua dự án của Keppel = mua một sản phẩm có nguồn vốn từ chính phủ Singapore."'),
  ('b14f2673-525d-56e7-bb54-d773a64f01ca','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Khang Điền (KDH)','developer','Thành lập: 2001, niêm yết HoSE 2010 · Index: VN30 · Vốn hóa: ~VND 28,500 tỷ (5/2026) · Track record: 20,000+ căn đã giao · Tỷ lệ hấp thụ: ~100% · Đòn bẩy: Debt/equity < 1.0

Khang Điền nổi tiếng với danh hiệu "ông hoàng sổ đỏ" — xây trước, bán sau, giao sổ hồng chỉ 3–6 tháng sau bàn giao. Tại Gladia, 67 sổ hồng đã được cấp ngày 7/11/2024 — TRƯỚC khi mở bán chính thức. Chuyên về biệt thự, nhà phố Đông và Nam HCM: Verosa Park, The Classia, Venica, Lucasta, Melosa, Jamila, Safira, The Privia. Hơn 50 dự án, 100% hấp thụ. Giải thưởng: "Developer of the Decade" tại PropertyGuru Vietnam Property Awards 2024; Vietnam National Brand 2022 & 2024; Top-10 Reputable Developer.

★ Talking point: "Khang Điền là chủ đầu tư duy nhất Việt Nam giao sổ hồng cho khách trước khi mở bán dự án — đó không phải may mắn, đó là kỷ luật. Chủ tịch KDH (bà Mai Trần Thanh Trang) xuất thân ngành luật."'),
  ('2230c263-ff5c-5141-bdba-5cb0992483cc','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Keppel Vietnam Fund','developer','First close: US$400M · Loại: Real estate private fund · Cổ phần Gladia: 49% cùng Keppel Land

Keppel Vietnam Fund (KVF) là quỹ BĐS tư nhân do Keppel quản lý, focus vào các cơ hội đầu tư BĐS chất lượng cao tại Việt Nam. First close US$400 triệu. KVF cùng Keppel Land sở hữu 49% trong liên doanh Gladia. Đây là cơ chế asset-light của Keppel theo Vision 2030.

★ Talking point: "Đây là cấu trúc tài chính cao cấp — vốn quỹ đầu tư private equity Singapore đang chảy vào dự án này."'),
  ('d163bd02-eead-544c-8441-a12ebab96f82','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Saigon Centre','comparable','Q1 — Keppel

Giai đoạn: 1996 (P1) & 2018 (P2) · Loại: Mixed-use: Văn phòng + Takashimaya · Tenant nổi bật: AIA, DBS, Mitsubishi, ANZ, Lazada, Lãnh sự Singapore · Occupancy: 100% năm

Tòa nhà landmark CBD Sài Gòn của Keppel. Takashimaya mall đặt tại đây — một trong những mall cao cấp nhất Sài Gòn. Lãnh sự quán Singapore đặt trụ sở tại Saigon Centre — chứng minh độ tin cậy của tòa nhà.

★ Talking point: "Saigon Centre có Takashimaya. Đây là trung tâm thương mại Nhật mà các dự án khu Đông luôn nhắc đến như giấc mơ — và Gladia có Keppel làm chủ đầu tư, chính là chủ của Takashimaya."'),
  ('bbce54ef-c4af-5dc8-94ef-36dd0cd8d039','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','The Estella','comparable','An Phú — 2012

Bàn giao: 2012 · Số căn: 719 · Hiện trạng: Đã bán hết, đã giao

Dự án Estella đầu tiên — bàn giao 2012, liên doanh Keppel + Tiến Phước. Là tiền đề cho Estella Heights (2018+).

★ Talking point: "Estella 2012 — Keppel đã giao đúng hẹn từ 14 năm trước. Đây là bằng chứng track record dài hạn."'),
  ('6b9eec87-339c-5a2b-9618-0d69aa015d1f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Estella Heights','comparable','An Phú — Keppel

Mở bán: 2/2015 @ VND 45 triệu/m² · Bàn giao P1: Q4/2018 · Bàn giao P2: 6/2019 · Hiện tại: VND 90–110 triệu/m² · Tăng giá: ~2× sau 11 năm

Mở bán 2015 ở mức VND 45 triệu/m² (~US$2,000). Hiện tại thứ cấp VND 90–110 triệu/m² — tăng ~2× trong 11 năm. Estella Place mall (cùng dự án) đạt BCA Green Mark đầu tiên tại Việt Nam — 1/2015.

★ Talking point: "Anh/Chị mua Estella Heights năm 2015 ở 45 triệu/m², hôm nay bán được 100 triệu/m² — gấp đôi sau 11 năm. Đó là track record của Keppel ngay tại Việt Nam."'),
  ('14264bdc-dd9c-5617-b109-26a84eb3d321','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Empire City Thủ Thiêm','comparable','Thủ Thiêm — Keppel JV

Diện tích: 14.6 ha · Số căn: 3,787 căn cao cấp · Landmark: Empire 88 — 88 tầng · Mở bán: 2017+ · Hiện tại: VND 125–200 triệu/m² (Cove cao hơn)

Dự án landmark tại CBD mới Thủ Thiêm. Liên doanh Keppel + Tien Phuoc + Tran Thai + Gaw Capital. Bàn giao Linden/Tilia từ 2020. Tỷ lệ hấp thụ >99%. Tòa Empire 88 (88 tầng) là landmark cao thứ nhì Sài Gòn.

★ Talking point: "Empire City đã giao và đang vận hành. Khi Anh/Chị mua Gladia, đây là chất lượng Anh/Chị sẽ nhận được."'),
  ('db2a84f5-38c4-5ea0-915e-986c6343e810','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Riviera Point','comparable','Q7 — Keppel

Hoàn thành: 2014+ · Số căn: ~1,900 · Hấp thụ: >93%

Dự án quy mô lớn tại Q7, liên doanh Keppel. Hấp thụ trên 93% tại thị trường khó.

★ Talking point: "Riviera Point ở Q7 — Keppel bán >93% trong thị trường khó. Đó là sức mạnh thương hiệu."'),
  ('758f1437-36be-55de-9e1a-67b31e98c6c9','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Palm City','comparable','An Phú — ⚠ Keppel đã thoái vốn 2025

Loại: 30.2 ha waterfront, ~5,000 căn · Bàn giao P1: 2017 · Bàn giao P2: 4/2019 · ⚠ Thoái vốn: 3/2025 — đổi thương hiệu Palm River

Lưu ý: Keppel đã thoái vốn Palm City vào 3/2025, lợi nhuận ròng ~S$55 triệu. Dự án được rebrand thành "Palm River" dưới Huong Viet Holdings. Đây là một phần chiến lược asset-light của Keppel — KHÔNG phải lỗi thực thi. Sales nên chuẩn bị trả lời khi khách hỏi.

★ Talking point: "Palm City đã được bàn giao đầy đủ và hoạt động tốt. Keppel thoái vốn không phải vì có vấn đề — mà vì chiến lược asset-light theo Vision 2030 của tập đoàn."'),
  ('9722efbb-65ee-57e6-b312-844059a00287','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Celesta Avenue / Heights','comparable','Nhà Bè — Keppel/Phú Long

Loại: Cao tầng · Hoàn thành: 2019 (Heights/Rise) · Celesta Avenue: Provisional BCA Green Mark 4/2024

Liên doanh Keppel + Phú Long. Celesta Avenue đạt BCA Green Mark tạm thời 4/2024 — minh chứng Keppel áp dụng tiêu chuẩn Singapore cho nhiều dự án VN.

★ Talking point: "Celesta Avenue đạt BCA Green Mark — chứng minh đây là chính sách hệ thống của Keppel, không phải chỉ Gladia."'),
  ('454308d0-e364-5112-8b5f-d6515ff57389','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Saigon Sports City','comparable','An Phú — ⚠ Trễ tiến độ

Diện tích: 64 ha · Số căn: 3,000+ · Vốn: US$500M · Khởi công: 2/2019 · ⚠ Tiến độ: Trễ — chỉ có nhà mẫu + cầu kết nối · Thoái vốn 70%: 2024–25

Cảnh báo: Đây là dự án Keppel trễ tiến độ rõ rệt. Sau 5 năm khởi công, mới chỉ xây nhà mẫu + cầu kết nối. Keppel thoái 70% vốn 2024-25 cho HTV Đại Phước (35%) và Vinobly (35%), giữ 30%. Thu hồi VND 7,130 tỷ (S$354M). Sales playbook: Khi khách đề cập, thừa nhận thẳng thắn. Khẳng định Gladia khác: Khang Điền pháp lý sạch, đã có sổ hồng, sản phẩm thấp tầng + cao tầng cụ thể, không phải township phức tạp.

★ Talking point: "Saigon Sports City là bài học Keppel đã học. Đó cũng là lý do Gladia là liên doanh với Khang Điền — chuyên gia pháp lý số 1 Việt Nam."'),
  ('a392d84c-df67-5237-8d92-ae565596a507','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Verosa Park','comparable','Q9 — Khang Điền

Loại: Biệt thự nhà phố · Hiện trạng: Đã giao, đầy đủ pháp lý

Một trong các dự án thấp tầng của Khang Điền tại Q9. Đại diện cho năng lực thấp tầng của KDH.

★ Talking point: "Verosa Park là minh chứng KDH chuyên về thấp tầng — và Gladia là phiên bản cao cấp hơn của Verosa."'),
  ('ab2b8213-bc22-5207-8c36-443fc5ba631b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','The Classia','comparable','Q9 — Khang Điền

Loại: Biệt thự · Hiện trạng: Bàn giao

Dự án biệt thự cao cấp của KDH tại Q9 (cũ). Tiêu biểu cho hệ sinh thái thấp tầng chuẩn KDH.'),
  ('c5168388-9b8e-5f15-8f07-78dae331a558','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','The Privia','comparable','Bình Tân — Khang Điền

Loại: Cao tầng

Dự án cao tầng tiêu biểu KDH — cho thấy năng lực phát triển cao tầng song song với thấp tầng.'),
  ('3188d74a-026c-55cf-842e-3e960774748c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','BCA Singapore','cert','Tên đầy đủ: Building & Construction Authority · Thành lập: 1/4/1999 · Cơ quan: Bộ Phát triển Quốc gia Singapore · Giải thưởng: Aspen Institute Energy Award 2010

BCA là cơ quan pháp luật của Singapore quản lý ngành xây dựng. Đặt tiêu chuẩn an toàn, chất lượng, bền vững. Năm 2010 là cơ quan chính phủ đầu tiên ngoài Bắc Mỹ nhận giải Aspen Institute về Năng lượng & Môi trường.

★ Talking point: "BCA là Bộ Xây dựng của Singapore. Khi Gladia được BCA cấp chứng nhận = chính phủ Singapore đã thẩm định và phê duyệt tiêu chuẩn của dự án."'),
  ('8baf102c-6698-5ce8-886c-d8cca2b15957','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','BCA Green Mark','cert','Ra mắt: 1/2005 · Áp dụng: 120+ dự án 10+ quốc gia · Bắt buộc tại SG: Mọi tòa >2,000m² GFA · 5 tiêu chí: Năng lượng, Nước, Môi trường, Chất lượng nội thất, Đổi mới

Hệ thống chứng nhận xanh quốc gia Singapore, ra mắt 1/2005. Bắt buộc tại Singapore cho mọi tòa >2,000m². Đã áp dụng tại Trung Quốc, Malaysia, Việt Nam, Brunei, Ấn Độ, Thái Lan, Saudi Arabia, Indonesia, Philippines, Tanzania. Cushman & Wakefield (trích BCA): Tòa Green Mark CBD có giá thuê cao hơn tới 12%, occupancy cao hơn. Tòa Super Low Energy hoàn vốn đầu tư bền vững trong 5–6 năm.

★ Talking point: "BCA Green Mark không phải nhãn hiệu marketing — đó là tiêu chuẩn bắt buộc tại Singapore. Có chứng nhận này = thuê cao hơn 12%."'),
  ('a050d294-79b1-5e93-9a3b-403d6cbdb6a5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Green Mark Gold','cert','Điểm số: 75–84 / 100 · Tiết kiệm năng lượng: 20–30% · Chi phí xây thêm: +8–15% · Mức độ: Chuẩn cho tòa Grade A Singapore

Green Mark Gold là một trong 4 hạng (Certified, Gold, GoldPlus, Platinum). Gold là chuẩn cho mọi tòa văn phòng Grade A tại Singapore. Tại Việt Nam, The Hallmark là tòa văn phòng đầu tiên đạt BCA Green Mark Gold.'),
  ('5ed321a3-4d82-55c4-b78f-e8013af00e22','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Green Mark for Districts','cert','Loại: Chứng nhận cấp khu đô thị · Phạm vi: Quy hoạch toàn khu, không chỉ tòa nhà · Tại Việt Nam: ⭐ Gladia là dự án ĐẦU TIÊN

Đây là hạng chứng nhận đặc biệt cho cả khu đô thị — không phải chỉ một tòa nhà. Đánh giá: quy hoạch giao thông, sử dụng năng lượng cấp khu, quản lý nước, vật liệu, môi trường. Gladia by the Waters là dự án ĐẦU TIÊN tại Việt Nam đạt chứng nhận này.

★ Talking point: "Đây là vũ khí định vị thương hiệu mạnh nhất. Gladia là dự án ĐẦU TIÊN tại VN đạt Green Mark for Districts. Không có đối thủ nào có chứng nhận cấp khu đô thị từ Singapore."'),
  ('b2df30b0-b5bd-5b78-bd6b-b1ad42423e06','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','LOTUS (VGBC)','cert','Ra mắt: 2010 — Vietnam Green Building Council · Số dự án đạt: 63 dự án tại VN (4/2024)

Hệ thống chứng nhận xanh của Việt Nam. Phù hợp khí hậu, vật liệu và quy định VN. Là chuẩn phổ biến trong nước, nhưng không có sự công nhận quốc tế như BCA Green Mark.

★ Talking point: "Đối thủ chỉ có LOTUS — chứng nhận trong nước. Gladia có cả LOTUS + BCA Green Mark for Districts từ Singapore."'),
  ('3ba4e9a8-a3a9-50b2-8654-1f7ee455e050','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','LEED (USGBC)','cert','Ra mắt: 1998 — USGBC · 4 hạng: Certified → Platinum

Hệ thống chứng nhận xanh của Mỹ — phổ biến toàn cầu. Tương đương BCA Green Mark về uy tín quốc tế.'),
  ('f3cacc81-305e-5128-a32f-dcbfb757beae','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Metro Line 1','metro','Bến Thành – Suối Tiên

Khai trương: 22/12/2024 · Chiều dài: 19.7 km, 14 trạm · Tàu: 17 đoàn tàu Hitachi · Tốc độ: 110 km/h trên cao, 80 km/h ngầm · Tác động giá: +15–20% YoY các vùng quanh trạm

Khai trương 22/12/2024 — tài trợ JICA. 14 trạm: 3 ngầm (Bến Thành, Nhà hát, Ba Son) + 11 trên cao. Tác động giá BĐS: Savills Q3/2025 — "khu Đông tăng 15-20% YoY." CBRE — "tại các trạm dọc tuyến giá tăng 50-200%." Thảo Điền hiện ở mức US$3,933-7,000+/m². Đề xuất mở rộng 41.4 km tới Đồng Nai + Long Thành — VND 60,261 tỷ đã được phê duyệt.

★ Talking point: "Metro 1 đã làm điều này cho Thảo Điền. Metro 6 sẽ làm điều tương tự cho Phú Hữu."'),
  ('51435925-cc2a-5a00-9c30-4b01d388138f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Metro Line 2','metro','Bến Thành – Tham Lương

Khởi công: 15/1/2026

Metro 2 đã chính thức khởi công 15/1/2026. Kết nối quận 1, 3, 10, 12, Tân Bình — phần kết nối với Metro 6 tại trạm Bà Quẹo.

★ Talking point: "Metro 6 sẽ giao Metro 2 tại Bà Quẹo. Khách Gladia có thể đi tàu thẳng đến Bến Thành không phải đổi tuyến nhiều."'),
  ('2e80db57-0974-50f3-a33a-9d2b18498397','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Metro Line 6 — GLADIA LINE','metro','Tân Sơn Nhất – Phú Hữu

Tổng: 53.8 km, 38 trạm · Phase 1: Tân Sơn Nhất → Phú Hữu · Khởi công: 2026 · Hoàn thành: 2030 · Trạm cuối: Phú Hữu (cạnh Gladia)

Tuyến metro chiến lược cho Gladia. Phase 1 ưu tiên 2026-2030: Tân Sơn Nhất → Phạm Văn Đồng → Phú Hữu. Giao cắt với Metro 2 (Bà Quẹo) và đường sắt Thủ Thiêm-Long Thành tại trạm Phú Hữu — nghĩa là một hành trình: Lên Metro 6 ở Phú Hữu, đổi sang express rail ở Phú Hữu/Thủ Thiêm, đến Long Thành. Một dịch vụ express 30 phút Tân Sơn Nhất → Long Thành đang nghiên cứu, đi qua Metro 6 + đường sắt TT-LT.

★ Talking point: "Khi Long Thành mở cửa, Tân Sơn Nhất quá tải, chính phủ KHÔNG có lựa chọn nào khác ngoài Metro 6. US$16 tỷ đầu tư cho sân bay sẽ bỏ ngỏ nếu không có metro."'),
  ('c07de8cc-f47d-52ee-b73f-6bd275616909','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Thủ Thiêm – Long Thành Rail','metro','Chiều dài: 42 km, 20 trạm · Vốn: VND 84,753 tỷ (US$3.2B) · Tốc độ: 120 km/h · Nhà đầu tư: PPP — Thaco · Khởi công: Cuối 2026 · Vận hành: 2030

Đường sắt express kết nối Thủ Thiêm với Long Thành Airport. 42 km, 20 trạm, tốc độ thiết kế 120 km/h. Giao cắt Metro 6 tại Phú Hữu/Thủ Thiêm — tạo thành mạng kết nối Tân Sơn Nhất – Phú Hữu – Long Thành.'),
  ('1f8d30da-fd93-57fa-966e-e64499aa44d9','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Vành đai 2','road','Vành đai nội đô tương lai

Tổng: ~64 km · Đã vận hành: 50 km (gồm Võ Chí Công) · Còn lại: 14 km — 4 đoạn · Đoạn Phú Hữu: 3.6 km, VND 9,800+ tỷ · Hoàn thành: ~2027–2029

Vành đai 2 sẽ trở thành vành đai nội đô khi hoàn thiện ~2027-2029. Gladia nằm trong Vành đai 2. Đoạn Phạm Văn Đồng – Gò Dưa đã tái khởi công, mục tiêu hoàn thành 30/4/2027.

★ Talking point: "Khi Vành đai 2 hoàn thành ~2027-2029, BĐS trong vành đai sẽ được định giá là NỘI ĐÔ, không còn là VEN ĐÔ. Gladia chính là trong vành đai đó."'),
  ('570e76d0-fbb9-5cf8-a877-e3cdb1681822','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Vành đai 3','road','Vành đai kinh tế — Bùng nổ 6/2026

Tổng: 76.34 km · Vốn: VND 75,378 tỷ (~US$3B) · Đoạn cao tốc: 8 làn, 100 km/h · Đoạn cao TP.HCM: 15 km — kỹ thuật 12/2025 · Mở cửa: 30/4/2026 · HOÀN THÀNH: 30/6/2026 · Đi qua: TP.HCM, Đồng Nai, Tây Ninh

Cao tốc 8 làn, tốc độ thiết kế 100 km/h. Phần đi qua TP Thủ Đức 15 km — đã thông kỹ thuật 12/2025, mở cửa trước 30/4/2026. Toàn tuyến hoàn thành 30/6/2026. Kết nối 5 cao tốc tỏa: HCMC–Trung Lương, HCMC–Long Thành–Dầu Giây, Bến Lức–Long Thành, HCMC–Mộc Bài, HCMC–Chơn Thành. Vinhomes Grand Park đã ghi nhận tăng tốc thị trường trực tiếp từ Vành đai 3.

★ Talking point: "Vành đai 3 hoàn thành tháng 6 năm nay (2026). Đây là vành đai kinh tế — sẽ làm cho Phú Hữu trở thành cửa ngõ logistic phía Nam."'),
  ('455f0bec-e3e1-5ba9-acd2-36166d3be6fc','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Vành đai 4','road','Vành đai công nghiệp

Tổng: ~159 km · Vốn Phase 1: ~VND 120,000 tỷ · Khởi công: Q2/2026 · Hoàn thành dự kiến: ~2031 · Mô hình: PPP · Tốc độ: 4 làn → mở rộng, 100 km/h

Vành đai công nghiệp kết nối Cái Mép-Thị Vải, Long Thành Airport, Biên Hòa, Bình Dương — chuyển hướng vận tải hàng hóa ra khỏi nội đô.

★ Talking point: "Vành đai 4 chỉ dành cho công nghiệp — nghĩa là Vành đai 2 (Gladia) chỉ dành cho dân cư và thương mại cao cấp. Phân vùng rõ ràng."'),
  ('a685ea87-40f2-5267-b4e4-88e66941ed1b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Võ Chí Công','road','Mặt tiền Gladia

Hiện tại: Một phần Vành đai 2 · Đường liên cảng: 5.9 km, 60m rộng, 12 làn · Vốn: ~VND 9,000 tỷ · Trình duyệt: 24/12/2025

Mặt tiền trực tiếp của Gladia. Hiện là một phần Vành đai 2. Đường liên cảng Cát Lái – Phú Hữu đã trình duyệt 24/12/2025: 5.9 km, mặt cắt 60m, 12 làn, tốc độ thiết kế 60 km/h, vốn ~VND 9,000 tỷ. Có cầu vượt cao 4 làn từ cảng Phú Hữu đến SP-ITC, 6 làn đến nút HLD; cầu Ba Cua mới 10 làn. Hiệu ứng: Container/xe tải sẽ đi qua "làn xanh" trên cao — bỏ khỏi Nguyễn Thị Định / Nguyễn Duy Trinh / Võ Chí Công mặt đất. Nâng cao chất lượng sống cho cư dân Gladia.

★ Talking point: "60 mét. Lớn hơn gấp đôi đường mặt tiền dự án đối thủ. Đây không phải số trừu tượng — đây là thực tế giao thông tương lai."'),
  ('b27cb50a-723f-5628-9adb-7ad3d2b03059','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Nút giao Mỹ Thủy 4 tầng','road','Cách Gladia ~2 km

Vốn: VND 3,622 tỷ · Loại: 4 tầng — đầu tiên VN · Kết nối: Nguyễn Thị Định + Đồng Văn Cống + Võ Chí Công · Hoàn thành: Q3/2026 (trễ từ 4/2026)

Nút giao 4 tầng đầu tiên Việt Nam: hầm chui + mặt đất + cầu vượt + ramps. Cửa ngõ vào Cát Lái Port (cảng container lớn nhất VN). Tách container khỏi giao thông đô thị — cùng tác dụng nâng cao chất lượng sống cho Gladia.

★ Talking point: "Mỹ Thủy 4 tầng — đầu tiên Việt Nam. Q3 năm nay xong. Đây là dự án xử lý kẹt xe ngay cửa ngõ Gladia."'),
  ('d17a00dc-281c-59dc-961a-f2f39d6a77d4','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Cầu Cát Lái','road','HCMC ↔ Đồng Nai

Khởi công: 15/1/2026 · Vốn (cùng Phú Mỹ 2): VND 40,000+ tỷ · Riêng Cát Lái: ~VND 20,614 tỷ (~US$830M) · Chiều dài: 11.6 km, cầu dây văng · Hoàn thành: 2028–2029

Cầu dây văng thay thế phà Cát Lái quá tải. Đã khởi công 15/1/2026. Bắt đầu từ Nguyễn Thị Định, cách Mỹ Thủy 400m; kết thúc tại cao tốc Bến Lức – Long Thành ở xã Đại Phước, Đồng Nai. Xây 4 năm → 2028-2029. 3 tác động: (1) Kết nối thẳng Long Thành Airport qua cao tốc BL-LT, (2) Container đi qua cầu + đường liên cảng, (3) Phú Hữu thành cửa ngõ HCMC ↔ Đồng Nai.

★ Talking point: "Cầu Cát Lái đã khởi công năm nay. 2028-2029 hoàn thành. Khi đó Gladia là cửa ngõ HCMC sang Đồng Nai — không phải vùng ven."'),
  ('5cb6d239-8f6a-5ee6-be07-2e1694cb5ddd','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Nút giao An Phú','road','Vốn: VND 3,400+ tỷ · Loại: 3 tầng · Hoàn thành: Q2/2026 · Đường hầm HC1-02: Đã mở

Nút giao 3 tầng kết nối Mai Chí Thọ với cao tốc HCMC – Long Thành – Dầu Giây. Q2/2026 hoàn thành.'),
  ('1dd8dcf7-8509-5528-9e4a-7b04a753ec7d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Đường liên cảng Cát Lái – Phú Hữu','road','Chiều dài: 5.9 km · Rộng: 60m, 12 làn · Vốn: ~VND 9,000 tỷ

Đường chuyên cho vận tải cảng — chuyển hướng container/xe tải khỏi đường dân sinh. Trình duyệt 24/12/2025.'),
  ('60d51813-8d63-52e2-8e65-b8bc04c8dd98','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Sân bay Long Thành','amenity','Quốc tế — 2026

Tổng vốn: ~US$16 tỷ (program) · Cách Gladia: ~40 km / 20 phút cao tốc · Diện tích: 5,000 ha · Phase 1: 25 triệu pax/năm · Phase 1 hoàn thành: 72% (3/2026) · Khai trương TM: Q4/2026 · Phase 3 (2050): 100 triệu pax — lớn nhất ĐNÁ

Tổng vốn ~US$16 tỷ (LƯU Ý: con số đúng — không phải $36 tỷ như đôi khi nghe nói). 3/2026 phase 1 đã hoàn thành 72%. Runway 1 đã xong 4/2025 (sớm 3 tháng). Chuyến bay kỹ thuật đầu 12/2025. Khai trương thương mại Q4/2026. 80% chuyến quốc tế HCM sẽ chuyển sang Long Thành. 14,000 việc làm cần lấp đến cuối 2026 — ACV đã bắt đầu tuyển từ 4/2026. Phase 3 đến 2050: 100 triệu hành khách/năm — sân bay lớn nhất Đông Nam Á, ngang Bangkok Suvarnabhumi và Singapore Changi.

★ Talking point: "Long Thành chính thức mở cửa Q4 năm nay. Trong 6 tháng tới, 14,000 chuyên gia + lao động cao cấp sẽ tới Đồng Nai — họ thuê nhà ở đâu? Gladia."'),
  ('5d67986f-ff80-54c5-9682-03e7a578baae','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Tân Sơn Nhất Airport','amenity','Hiện tại: Quá tải nghiêm trọng · Sau Long Thành: 20% chuyến quốc tế giữ lại

Sân bay hiện hữu — quá tải. Sau khi Long Thành mở cửa, 80% quốc tế chuyển sang Long Thành, 20% còn lại + nội địa giữ tại Tân Sơn Nhất. Metro 6 kết nối Tân Sơn Nhất → Phú Hữu = Gladia có quyền truy cập rapid transit đến cả hai sân bay.'),
  ('4bc28cdc-b3c3-5304-a440-aff7f66a0364','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Saigon Hi-Tech Park (SHTP)','amenity','Cách Gladia 5–8 km

Diện tích: 913 ha (P1: 300, P2: 613) · Số nhân sự: ~25,000+ chuyên gia · Vốn tích lũy: US$7.1 tỷ+ · Xuất khẩu tích lũy: US$45 tỷ+ · % xuất khẩu HCM hi-tech: 94%

Tenant lớn: Intel (nhà máy chip lớn nhất thế giới, $1B+); Samsung Electronics HCMC Complex (SEHC) $2B; Nidec Nhật $500M kế hoạch 20,000 công nhân; Sanofi Pháp; Sonion Đan Mạch 2,000 công nhân; Datalogic, Microchip, FPT, Nanogen. Mức lương: Kỹ sư cao cấp + quản lý cấp trung Intel/Samsung/Nidec: US$1,500-4,000+/tháng — tệp thuê uy tín ngay cạnh Gladia. Tầm nhìn 2030: trung tâm khoa học công nghệ quốc tế. 2045: hi-tech park net-zero đầu tiên Việt Nam.

★ Talking point: "25,000 chuyên gia SHTP — đó là 25,000 hợp đồng thuê tiềm năng ngay cạnh Gladia. Họ muốn ở đâu? An toàn, xanh, mật độ thấp. Đó chính là Gladia."'),
  ('5396ba6f-4a9d-5d6d-878d-b14eb28c45d9','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Cảng Cái Mép – Thị Vải','amenity','Đặc điểm: Cảng nước sâu DUY NHẤT VN · Tuyến đến Mỹ/EU: Trực tiếp (chỉ sau Singapore/Malaysia ĐNÁ) · Throughput 2024: 6.5 triệu TEU (+33% YoY) · Tăng trưởng 9T/2025: +18% YoY

Cảng nước sâu duy nhất VN có dịch vụ trực tiếp tới Mỹ/EU. 22 bến hoạt động, 117.8 triệu tấn/năm. 2024: 6.5 triệu TEU (+33% YoY). 9 tháng/2025: +18% YoY (VPA). Cai Mep Ha Logistics Center: 1,763 ha quy hoạch bao gồm free-trade zone.

★ Talking point: "Gladia nằm trên trục logistics HCMC port → Cái Mép. Khi xuất khẩu tăng = nhu cầu chuyên gia tại HCM tăng = nhu cầu nhà ở cao cấp tăng."'),
  ('5d2c743a-b05c-5c24-b897-9ad43150b13e','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Cảng Cát Lái','amenity','Đặc điểm: Cảng container lớn nhất VN · Kết nối Gladia: Qua Mỹ Thủy + đường liên cảng

Cảng container lớn nhất Việt Nam. Khách logistics doanh nhân — segment target chính của Gladia.'),
  ('8a00c0b3-f34d-5578-a6e6-e5f896ceab61','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Bệnh viện Quốc tế','amenity','⚠ Cần xác minh

Trạng thái: ⚠ Chưa xác minh được · BV gần nhất xác nhận: AIH, Vinmec Central Park, FV

Lưu ý: Tham chiếu "Bệnh viện Quốc tế Phú Hữu 2028" chưa thể xác minh trong nguồn công khai. Có thể là tiện ích trong masterplan Palm City cũ, hoặc dự án chưa công bố, hoặc định vị marketing. BV gần được xác nhận: American International Hospital (Q2), Vinmec Central Park (Q2), FV Hospital, Hạnh Phúc International (tại Estella Place). Sales: Xác minh với phòng KD Khang Điền trước khi dùng trong tài liệu khách hàng.

★ Talking point: "Tham chiếu BV Quốc tế Phú Hữu cần xác minh. Hiện tại trong khu vực: AIH Q2, Vinmec Q2, FV — đều là tiêu chuẩn quốc tế."'),
  ('31827077-73ea-50c1-b530-0722f2c48e5f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','TP Thủ Đức','location','Thành lập: 12/2020 · Diện tích: 211.56 km² · Dân số 2030: 1.8M → 2.6M (2040) → 3M · Masterplan duyệt: 21/1/2025 · Gọi vốn: 535 dự án ~US$31.6 tỷ

Thành phố ĐẦU TIÊN trong thành phố tại Việt Nam — gộp Q2 + Q9 + Thủ Đức cũ. 9 phân vùng phát triển / 11 khu chiến lược. Trong đó: Bình Trưng Tây (Gladia) = cầu nối giữa Thủ Thiêm CBD và khu logistic cảng. Mục tiêu giao thông công cộng đáp ứng 50-60% nhu cầu đi lại đến 2040.

★ Talking point: "TP Thủ Đức = TP đầu tiên trong TP của VN. Định vị là innovation hub. Gladia ở trung tâm masterplan này."'),
  ('f3ef550d-31ac-5400-8dd7-b87309c9da98','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Phú Hữu Ward','location','Khu vực: Q9 cũ (nay TP Thủ Đức) · Giá hiện tại: VND 28-150 triệu/m² tùy mặt tiền

Phường Phú Hữu — khu vực hiện tại đang ở giai đoạn đầu chu kỳ tăng giá. Bao gồm cảng Phú Hữu, một phần trục Võ Chí Công. Giá tham khảo 2025: nội bộ Gò Cát/Bưng Ông Thoàn: VND 28-50 triệu/m²; mặt tiền Nguyễn Duy Trinh: VND 50-150 triệu/m²; mặt tiền Liên Phường (cạnh Vinhomes GP): tới ~VND 95 triệu/m².

★ Talking point: "Phú Hữu đang ở chân chu kỳ tăng giá — Diamond Island, Estella đều bắt đầu từ chân tương tự năm 2014-2015."'),
  ('ae73b1d8-3f7a-5f35-bcac-b03c07810160','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Bình Trưng Đông','location','Khu vực: Q2 cũ, nay TP Thủ Đức · Vị trí Gladia: Mặt tiền Võ Chí Công

Địa chỉ thực tế của Gladia. Nằm trong khu quy hoạch Cát Lái – Bình Trưng Đông 66.08 ha. Khoảng cách: 3 phút Thủ Thiêm, 10 phút Phú Mỹ Hưng, 20 phút Bến Thành, 20 phút Long Thành cao tốc.'),
  ('c51558f3-0885-5a97-8d2c-65228554b7d5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Thủ Thiêm','location','Vai trò: CBD tài chính mới của HCM

Trung tâm tài chính mới của HCM — Empire City (Keppel) là dự án landmark tại đây. Cách Gladia 3 phút qua cầu Thời Đại.'),
  ('d632342e-7b2f-54f1-b36b-5545e6ecf3ba','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Thảo Điền','location','Giá hiện tại: US$3,933-7,000+/m² · Sau Metro 1: +50 đến +200%

Khu expat truyền thống. Sau Metro 1, giá tăng 50-200% các vùng dọc tuyến. Là bài học cho Phú Hữu sau Metro 6.

★ Talking point: "Thảo Điền hôm nay là Phú Hữu năm 2030. Cùng pattern: trạm metro, expat community, chuẩn quốc tế."'),
  ('c284a55c-690f-519b-907c-711662abe3e4','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','An Phú','location','Vai trò: Khu cao cấp Q2 cũ · Dự án landmark: Estella Heights (Keppel), Palm City

Khu cao cấp gần CBD — nơi Estella Heights và Palm City đặt nền móng cho thương hiệu Keppel tại VN.'),
  ('3a35c8fe-8e16-59ef-969c-2da4e5c3b62e','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Đảo Kim Cương','comparable','Q2 — Kusto Home

Mở bán: ~2014-2016 (P2) · Giá launch: US$1,800-2,200/m² (VND 40-50tr/m²) · Hiện tại: VND 90-120 triệu/m² · Tăng: ~2.0-2.5× trong 10 năm

Bài học vàng: Mở bán giai đoạn 2 ở mức VND 40-50 triệu/m². Hôm nay VND 90-120 triệu/m². Tăng 2.0-2.5× trong 10 năm.

★ Talking point: "Anh/Chị nhớ Đảo Kim Cương năm 2015? Ai cũng nói xa, đường khó. Mua 40-50tr/m², giờ 100-120tr/m². Phú Hữu hôm nay = Đảo Kim Cương năm 2015."'),
  ('7b90ce58-c6ed-5ee6-80fc-ab6985db141a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Vista Verde','comparable','Q2 — CapitaLand

Mở bán: 7/2014 · Giá launch: US$1,500-2,000/m² · Hiện tại: VND 54-87 triệu/m² · Tăng: ~2×+ trong 10 năm

Một case study tăng giá quan trọng. Mở bán 2014, hiện tại trung bình ~VND 66 triệu/m² (8/2022).'),
  ('8774ce3c-2407-58a6-87e0-8a7e0f2ea485','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Masteri Thảo Điền','comparable','Mở bán: 2014 @ VND 35tr/m² · Hiện tại: VND 60-100+ tr/m² · Tăng: ~2-3×

Mở bán 2014 ở mức 35tr/m². Sau khi Metro 1 hoàn thành — giá lên 60-100+ triệu/m². Tăng 2-3 lần trong 10-11 năm.'),
  ('7cf6ade3-ea8a-533d-bb2e-c672d07ccc61','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Vinhomes Grand Park','comparable','Q9 — Floor Reference

Mở bán: 2019 (Sapphire) @ VND 30-35tr/m² · Origami: VND 34tr/m² · Căn hộ hiện tại: VND 50-80tr/m² · Villa: US$740K (150m²) — US$1.5M (302m²) · Tăng: ~1.5-2× trong 5-6 năm

Tham chiếu giá sàn dưới Gladia. Gladia định giá CAO HƠN Vinhomes GP nhưng THẤP HƠN An Phú/Thảo Điền hiện tại — kịch bản upside là hội tụ với An Phú trong 5-7 năm.'),
  ('89b74583-594a-509e-b048-484a62e14dc0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Thạnh Mỹ Lợi','comparable','Q2 — Câu chuyện vàng

Đất biệt thự 2015: ~VND 50-80tr/m² · Hiện tại (nội bộ): VND 100-180tr/m² · Hiện tại (mặt sông): tới VND 400tr/m² · Tăng: 3-5× trong 10 năm

Bài học mạnh nhất. Năm 2015 ai cũng nói Thạnh Mỹ Lợi xa, kẹt xe. Mặt sông Trần Quý Kiên / Trương Văn Bang nay đạt VND 400 triệu/m². Tăng 3-5 lần trong 10 năm.

★ Talking point: "Thạnh Mỹ Lợi là bài học mạnh nhất. Cùng câu chuyện kẹt xe, cùng câu chuyện hạ tầng. Ai mua năm 2015, hôm nay thắng lớn."'),
  ('cb586749-4363-5a46-ae26-719528505670','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Masterplan TP Thủ Đức 2040','policy','Duyệt: 21/1/2025 — Quyết định 202/QĐ-TTg · Tầm nhìn: 2040, định hướng 2050 · Gọi vốn: 535 dự án ~US$31.6 tỷ · Khu Bình Trưng Tây: Gồm Gladia

Quy hoạch chính thức được Thủ tướng phê duyệt 21/1/2025. 9 phân vùng. Bình Trưng Tây (gồm Gladia) là cầu nối giữa CBD Thủ Thiêm và khu logistic cảng.'),
  ('70097cf3-8705-59a6-9654-f857b87b61e9','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Bảng giá đất mới 1/1/2026','policy','Hiệu lực: 1/1/2026 · Tăng: Lên đến 8× bảng giá cũ

Bảng giá đất HCM mới có hiệu lực 1/1/2026, tăng lên đến 8 lần so với bảng cũ. Tác động: tham chiếu thị trường mới, tăng tốc reset giá. Tích cực cho định giá lại; tăng ma sát cho giao dịch 2026.'),
  ('952992bd-30cf-513a-a154-ce1c2bdf7352','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','Net-Zero 2050','policy','Cam kết: VN tại COP26 · Keppel: Cam kết đồng hành

Việt Nam đã cam kết net-zero vào 2050 tại COP26. Keppel đã cam kết đồng hành — SHTP đặt mục tiêu net-zero hi-tech park đầu tiên VN vào 2045.

★ Talking point: "Khi VN net-zero 2050, BĐS không có chứng nhận xanh sẽ mất giá trị. Gladia với BCA Green Mark = chống mất giá tương lai."');

insert into map_edges (id, org_id, project_id, source_id, target_id, kind) values
  ('38b12365-9d63-5007-ac6c-7dc34d9a8228','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','3dc3fc74-a162-5f0f-87a9-161954c8c052','supports'),
  ('360844ca-832c-5177-9860-4dbf32c2dd62','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','b14f2673-525d-56e7-bb54-d773a64f01ca','supports'),
  ('7d4c904e-d61b-55e8-9fe5-c3dd7bcb113d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','2230c263-ff5c-5141-bdba-5cb0992483cc','supports'),
  ('982df9f9-aadb-5593-85fe-8df8effaf84d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','5ed321a3-4d82-55c4-b78f-e8013af00e22','supports'),
  ('d0f818d8-7f97-53a2-ac4a-5cfc2830a825','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','ae73b1d8-3f7a-5f35-bcac-b03c07810160','part_of'),
  ('19fd0d79-eef9-54e0-bf39-c79e9da828bc','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','f3ef550d-31ac-5400-8dd7-b87309c9da98','near'),
  ('e4d934b5-7e1a-598c-a616-ecad001112d0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('e32ea9e9-8fd6-5a77-90a0-7ac2addbbd24','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','a685ea87-40f2-5267-b4e4-88e66941ed1b','part_of'),
  ('5bd33563-8291-5841-a70d-93aed30a7d13','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','2e80db57-0974-50f3-a33a-9d2b18498397','near'),
  ('07793470-7911-5a98-af57-81fd5a61d42f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','b27cb50a-723f-5628-9adb-7ad3d2b03059','near'),
  ('b45df8a2-0ae1-599f-b29f-1b1666490f4d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','1f8d30da-fd93-57fa-966e-e64499aa44d9','part_of'),
  ('3d989318-1096-5964-bea2-85f8ff538954','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','4bc28cdc-b3c3-5304-a440-aff7f66a0364','near'),
  ('047e382e-fcaa-5e03-a7e9-459eb57d9348','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','58c1193c-245e-503c-b4d9-02d675092b21','part_of'),
  ('3d96b65d-16d8-563e-8181-090bc0de03ea','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','58c1193c-245e-503c-b4d9-02d675092b21','d5b6bff3-fa3a-512a-925e-d79d3b7588df','supports'),
  ('f94b7b4a-d457-54ad-963f-ec1fdaea6a42','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','2230c263-ff5c-5141-bdba-5cb0992483cc','58c1193c-245e-503c-b4d9-02d675092b21','supports'),
  ('626a73b6-cd21-5692-a1bd-57448c1f4b59','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','d163bd02-eead-544c-8441-a12ebab96f82','supports'),
  ('ffb4daed-290d-5c5b-90a1-5a2c72243afa','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','bbce54ef-c4af-5dc8-94ef-36dd0cd8d039','supports'),
  ('f890ea9d-aeda-516c-bb0c-bac4ff36718e','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','6b9eec87-339c-5a2b-9618-0d69aa015d1f','supports'),
  ('af7e9c73-b312-57f0-a556-44c7dbaec468','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','14264bdc-dd9c-5617-b109-26a84eb3d321','supports'),
  ('2ec5f00d-b450-5177-b99f-31084c12a8e6','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','db2a84f5-38c4-5ea0-915e-986c6343e810','supports'),
  ('a0fb1194-953c-53ed-a775-5c1185db36cb','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','758f1437-36be-55de-9e1a-67b31e98c6c9','supports'),
  ('1f593ab6-9500-57b7-aec6-3047aa43e664','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','9722efbb-65ee-57e6-b312-844059a00287','supports'),
  ('6cb0de46-4a98-546a-bb7e-0e6a7a2897c7','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dc3fc74-a162-5f0f-87a9-161954c8c052','454308d0-e364-5112-8b5f-d6515ff57389','supports'),
  ('44344599-75c4-501c-a91b-e29204b2c146','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','b14f2673-525d-56e7-bb54-d773a64f01ca','a392d84c-df67-5237-8d92-ae565596a507','supports'),
  ('170c13ff-a01f-565c-8e06-9e39d1c89f6d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','b14f2673-525d-56e7-bb54-d773a64f01ca','ab2b8213-bc22-5207-8c36-443fc5ba631b','supports'),
  ('d69ae141-34d8-58a6-b2f1-4dcd3e4c185b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','b14f2673-525d-56e7-bb54-d773a64f01ca','c5168388-9b8e-5f15-8f07-78dae331a558','supports'),
  ('1949ae7e-98b0-531d-aab8-142b68841fb5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','5ed321a3-4d82-55c4-b78f-e8013af00e22','8baf102c-6698-5ce8-886c-d8cca2b15957','part_of'),
  ('c3bdae17-83d5-59dc-b164-653b539ef8e5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','a050d294-79b1-5e93-9a3b-403d6cbdb6a5','8baf102c-6698-5ce8-886c-d8cca2b15957','part_of'),
  ('a8ade273-e7b0-58ed-84cf-08152f4132d8','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','8baf102c-6698-5ce8-886c-d8cca2b15957','3188d74a-026c-55cf-842e-3e960774748c','part_of'),
  ('ca9c55f5-5372-522a-bfd2-864e952d576c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','6b9eec87-339c-5a2b-9618-0d69aa015d1f','8baf102c-6698-5ce8-886c-d8cca2b15957','supports'),
  ('a8611247-8aa5-5c29-8c12-fdd384199339','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','9722efbb-65ee-57e6-b312-844059a00287','8baf102c-6698-5ce8-886c-d8cca2b15957','supports'),
  ('b04d4cd3-885f-5845-b729-d199b8c961db','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','2e80db57-0974-50f3-a33a-9d2b18498397','5d67986f-ff80-54c5-9682-03e7a578baae','part_of'),
  ('f093da10-5cf4-5b12-b3a4-e41e1f03fa1f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','2e80db57-0974-50f3-a33a-9d2b18498397','f3ef550d-31ac-5400-8dd7-b87309c9da98','part_of'),
  ('7cd254f7-d9cd-53bb-90f6-406d5de22efb','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','2e80db57-0974-50f3-a33a-9d2b18498397','51435925-cc2a-5a00-9c30-4b01d388138f','near'),
  ('5e688bd1-d1b9-51c7-a1ca-b1dc54feed2b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','2e80db57-0974-50f3-a33a-9d2b18498397','c07de8cc-f47d-52ee-b73f-6bd275616909','near'),
  ('6301cedf-ae88-55b1-ace1-849926ea499f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','c07de8cc-f47d-52ee-b73f-6bd275616909','60d51813-8d63-52e2-8e65-b8bc04c8dd98','part_of'),
  ('8535111e-75ac-5ef2-8756-03e06c3ccb18','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','c07de8cc-f47d-52ee-b73f-6bd275616909','c51558f3-0885-5a97-8d2c-65228554b7d5','part_of'),
  ('56614d01-1326-5981-b187-0acf63278ac2','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','f3cacc81-305e-5128-a32f-dcbfb757beae','d632342e-7b2f-54f1-b36b-5545e6ecf3ba','near'),
  ('78f7a4fd-3cf7-51a3-9abf-0a71c05df677','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','1f8d30da-fd93-57fa-966e-e64499aa44d9','a685ea87-40f2-5267-b4e4-88e66941ed1b','part_of'),
  ('4454e92c-9db1-5eef-8c0b-2240adfa461c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','570e76d0-fbb9-5cf8-a877-e3cdb1681822','31827077-73ea-50c1-b530-0722f2c48e5f','near'),
  ('cce26736-52a9-504e-b802-75372356a0a1','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','570e76d0-fbb9-5cf8-a877-e3cdb1681822','60d51813-8d63-52e2-8e65-b8bc04c8dd98','near'),
  ('354a9077-254c-5589-aeaf-3f6e7ad86c05','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','455f0bec-e3e1-5ba9-acd2-36166d3be6fc','5396ba6f-4a9d-5d6d-878d-b14eb28c45d9','near'),
  ('9bd0c1df-288a-59e3-b0ec-78adbdccf7b5','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','455f0bec-e3e1-5ba9-acd2-36166d3be6fc','60d51813-8d63-52e2-8e65-b8bc04c8dd98','near'),
  ('0a96faf3-2cce-5bfd-801f-f05f22adf30a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','d17a00dc-281c-59dc-961a-f2f39d6a77d4','60d51813-8d63-52e2-8e65-b8bc04c8dd98','near'),
  ('063e11df-e50b-5098-ab3a-e5d626af973c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','d17a00dc-281c-59dc-961a-f2f39d6a77d4','b27cb50a-723f-5628-9adb-7ad3d2b03059','near'),
  ('9509149d-d03c-5a24-be0b-fb9bc7426234','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','1dd8dcf7-8509-5528-9e4a-7b04a753ec7d','5d2c743a-b05c-5c24-b897-9ad43150b13e','near'),
  ('dc50d713-9397-50b0-92d3-d66b5830fe51','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','1dd8dcf7-8509-5528-9e4a-7b04a753ec7d','f3ef550d-31ac-5400-8dd7-b87309c9da98','near'),
  ('ab848b99-38ed-5f9f-acaa-1d22ab384a91','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','b27cb50a-723f-5628-9adb-7ad3d2b03059','5d2c743a-b05c-5c24-b897-9ad43150b13e','near'),
  ('aba39403-7d0d-55c5-a9b2-0a91cb3e0a15','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','5cb6d239-8f6a-5ee6-be07-2e1694cb5ddd','60d51813-8d63-52e2-8e65-b8bc04c8dd98','near'),
  ('dee981ec-2872-50b7-8b52-83d6a89c4050','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','60d51813-8d63-52e2-8e65-b8bc04c8dd98','5396ba6f-4a9d-5d6d-878d-b14eb28c45d9','near'),
  ('77adcd83-7813-58a3-a8b1-f1b0b2be6b7d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','4bc28cdc-b3c3-5304-a440-aff7f66a0364','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('87b6a490-bacd-5d4e-a782-d5d3f8a4801b','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','5d2c743a-b05c-5c24-b897-9ad43150b13e','5396ba6f-4a9d-5d6d-878d-b14eb28c45d9','near'),
  ('3b474a37-2309-5bed-97c8-f6735d872a39','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','ae73b1d8-3f7a-5f35-bcac-b03c07810160','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('8f78a64d-e632-553b-ac1e-8219da86f875','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','f3ef550d-31ac-5400-8dd7-b87309c9da98','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('fe2f3e34-b5b9-5b8d-a09d-a2ec197350a8','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','c51558f3-0885-5a97-8d2c-65228554b7d5','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('c9acbe5b-0da0-5794-b508-ddc1c6436bc1','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','d632342e-7b2f-54f1-b36b-5545e6ecf3ba','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('333c4d84-0f3d-5855-b8bd-b33aa73ccc9f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','c284a55c-690f-519b-907c-711662abe3e4','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('fc46ff0f-15ae-525c-a4f7-2b87a450916c','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3a35c8fe-8e16-59ef-969c-2da4e5c3b62e','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('07a6d0b7-adf5-5cc6-b2ad-1e2e2ca0601f','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','7b90ce58-c6ed-5ee6-80fc-ab6985db141a','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('1960ae6c-980b-554d-843e-5a6ee36666b0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','8774ce3c-2407-58a6-87e0-8a7e0f2ea485','d632342e-7b2f-54f1-b36b-5545e6ecf3ba','part_of'),
  ('e391a70d-f79e-5d73-a286-f9cbdbcf23ec','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','6b9eec87-339c-5a2b-9618-0d69aa015d1f','c284a55c-690f-519b-907c-711662abe3e4','part_of'),
  ('5d1c5597-9a96-5511-8392-345ad4f197ce','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','14264bdc-dd9c-5617-b109-26a84eb3d321','c51558f3-0885-5a97-8d2c-65228554b7d5','part_of'),
  ('f5e92e53-edf7-5019-9655-ea1e06580e1a','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','758f1437-36be-55de-9e1a-67b31e98c6c9','c284a55c-690f-519b-907c-711662abe3e4','part_of'),
  ('0e9e43d3-5305-5f58-b48b-39cf4f21b6de','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','7cf6ade3-ea8a-533d-bb2e-c672d07ccc61','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('3d112944-2df2-5cfb-b0cc-2140a6fec8d0','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','89b74583-594a-509e-b048-484a62e14dc0','31827077-73ea-50c1-b530-0722f2c48e5f','part_of'),
  ('f56a4eb8-5f3b-510f-9352-fa829c7416c6','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','8774ce3c-2407-58a6-87e0-8a7e0f2ea485','f3cacc81-305e-5128-a32f-dcbfb757beae','near'),
  ('15363958-1d9e-58a3-8567-308569841d49','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','31827077-73ea-50c1-b530-0722f2c48e5f','cb586749-4363-5a46-ae26-719528505670','supports'),
  ('c9aa1fda-0b68-5e72-8ac7-2f59d5da92f2','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','3dcde88f-fc3b-5011-9f09-f7d8960d0d46','70097cf3-8705-59a6-9654-f857b87b61e9','supports'),
  ('7cac83ad-4fe2-5b1e-aa14-a00d6124bd1d','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','58c1193c-245e-503c-b4d9-02d675092b21','952992bd-30cf-513a-a154-ce1c2bdf7352','supports'),
  ('49c0e80c-4d61-5f08-8bec-a6e1243631bd','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','6b9eec87-339c-5a2b-9618-0d69aa015d1f','bbce54ef-c4af-5dc8-94ef-36dd0cd8d039','part_of'),
  ('e351cafc-92bf-559e-ac66-3f99da792d27','00000000-0000-0000-0000-0000000000d0','00000000-0000-0000-0000-00000000a001','6b9eec87-339c-5a2b-9618-0d69aa015d1f','14264bdc-dd9c-5617-b109-26a84eb3d321','relates');
