// Generates a per-project knowledge-map seed (supabase/seed_knowledge_<key>.sql)
// from an authored knowledge-map HTML export (the standalone force-graph file).
// Project-agnostic: pass the project's id + a uuid prefix so node/link ids are
// deterministic per project and never collide across projects.
//
//   node scripts/gen_project_map.mjs \
//     --src docs/knowledge/cosmo-central.html \
//     --out supabase/seed_knowledge_cosmo.sql \
//     --project-id 00000000-0000-0000-0000-00000000a006 \
//     --prefix cosmo
//
// Targets the first-class schema (knowledge_nodes/knowledge_links): facts,
// talkpoint and description are stored as separate columns (not a merged note).
// Output is idempotent: deletes the project's existing map rows then inserts the
// full set, with deterministic UUIDv5 ids so re-runs are stable.

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const SRC = arg("src");
const OUT = arg("out");
const PROJECT_ID = arg("project-id");
const PREFIX = arg("prefix");
if (!SRC || !OUT || !PROJECT_ID || !PREFIX) {
  throw new Error("usage: --src <html> --out <sql> --project-id <uuid> --prefix <key>");
}

// Namespace for UUIDv5 so map ids are deterministic across runs.
const NS = "6ba7b810-9dad-11d1-80b4-00c04fd430c8";

// --- deterministic UUIDv5 (SHA-1) -----------------------------------------
function uuidv5(name, namespace) {
  const nsBytes = Buffer.from(namespace.replace(/-/g, ""), "hex");
  const hash = createHash("sha1");
  hash.update(nsBytes);
  hash.update(Buffer.from(name, "utf8"));
  const b = hash.digest().subarray(0, 16);
  b[6] = (b[6] & 0x0f) | 0x50; // version 5
  b[8] = (b[8] & 0x3f) | 0x80; // variant
  const h = b.toString("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}
const nodeUuid = (id) => uuidv5(`${PREFIX}-node:${id}`, NS);
const edgeUuid = (s, t) => uuidv5(`${PREFIX}-edge:${s}->${t}`, NS);

// --- extract NODES / LINKS array literals from the HTML --------------------
const html = readFileSync(SRC, "utf8");
function sliceArray(marker) {
  const start = html.indexOf(marker);
  if (start === -1) throw new Error(`marker not found: ${marker}`);
  const open = html.indexOf("[", start);
  let depth = 0;
  for (let i = open; i < html.length; i++) {
    const c = html[i];
    if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) return html.slice(open, i + 1);
    }
  }
  throw new Error(`unterminated array for ${marker}`);
}
// eslint-disable-next-line no-eval
const NODES = eval(sliceArray("const NODES ="));
// eslint-disable-next-line no-eval
const LINKS = eval(sliceArray("const LINKS ="));

// --- strip the authored HTML in descriptions to plain text -----------------
function stripHtml(s) {
  return (s || "")
    .replace(/<\/(p|li|ul|div)>/gi, " ")
    .replace(/<li[^>]*>/gi, "• ")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}

const sqlStr = (s) => (s == null || s === "" ? "null" : `'${String(s).replace(/'/g, "''")}'`);
// facts [[k,v],...] -> jsonb [{key,value}]
const factsJson = (facts) =>
  `'${JSON.stringify((facts || []).map(([key, value]) => ({ key, value }))).replace(/'/g, "''")}'::jsonb`;

// --- build SQL -------------------------------------------------------------
const out = [];
out.push(
  `-- ${PREFIX} knowledge map — generated by scripts/gen_project_map.mjs (do not edit by hand).`,
  "-- First-class schema: facts/talkpoint/description as separate columns.",
  "-- Idempotent: clears this project's map then reinserts with deterministic UUIDv5 ids.",
  "",
  `delete from knowledge_links where project_id = '${PROJECT_ID}';`,
  `delete from knowledge_nodes where project_id = '${PROJECT_ID}';`,
  "",
  "insert into knowledge_nodes (id, project_id, node_key, label, category, sub_label, facts, talkpoint, description, sort_order) values",
);

const nodeRows = NODES.map((n, i) =>
  `  ('${nodeUuid(n.id)}','${PROJECT_ID}',${sqlStr(n.id)},${sqlStr(n.label)},${sqlStr(n.cat)},` +
  `${sqlStr(n.sub)},${factsJson(n.facts)},${sqlStr(n.talkpoint)},${sqlStr(stripHtml(n.desc))},${i})`,
);
out.push(nodeRows.join(",\n") + ";");
out.push("");

// Keep only links whose endpoints exist, de-duplicated by (source,target).
const ids = new Set(NODES.map((n) => n.id));
const seen = new Set();
const edgeRows = [];
for (const [s, t, label] of LINKS) {
  if (!ids.has(s) || !ids.has(t)) continue;
  const key = `${s}->${t}`;
  if (seen.has(key)) continue;
  seen.add(key);
  edgeRows.push(
    `  ('${edgeUuid(s, t)}','${PROJECT_ID}','${nodeUuid(s)}','${nodeUuid(t)}',${sqlStr(label)})`,
  );
}
out.push("insert into knowledge_links (id, project_id, source_node, target_node, label) values");
out.push(edgeRows.join(",\n") + ";");
out.push("");

writeFileSync(OUT, out.join("\n"));
console.log(`wrote ${OUT}: ${NODES.length} nodes, ${edgeRows.length} links`);
