// Generates a per-project knowledge-map seed (supabase/seed_<key>_map.sql) from
// an authored knowledge-map HTML export (the standalone force-graph file).
// Project-agnostic: pass the project's ids + a uuid prefix so node/edge ids are
// deterministic per project and never collide across projects.
//
//   node scripts/gen_project_map.mjs \
//     --src docs/knowledge/cosmo-central.html \
//     --out supabase/seed_cosmo_map.sql \
//     --project-id 00000000-0000-0000-0000-00000000a006 \
//     --org-id 00000000-0000-0000-0000-0000000000d0 \
//     --prefix cosmo
//
// Output is idempotent: it deletes the project's existing map rows then inserts
// the full set, with deterministic UUIDv5 ids so re-runs are stable.

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

const SRC = arg("src");
const OUT = arg("out");
const PROJECT_ID = arg("project-id");
const ORG_ID = arg("org-id", "00000000-0000-0000-0000-0000000000d0");
const PREFIX = arg("prefix");
if (!SRC || !OUT || !PROJECT_ID || !PREFIX) {
  throw new Error("usage: --src <html> --out <sql> --project-id <uuid> --prefix <key> [--org-id <uuid>]");
}

// Namespace for UUIDv5 so map-node/edge ids are deterministic across runs.
const NS = "6ba7b810-9dad-11d1-80b4-00c04fd430c8";

// --- deterministic UUIDv5 (SHA-1) -----------------------------------------
function uuidv5(name, namespace) {
  const nsBytes = Buffer.from(namespace.replace(/-/g, ""), "hex");
  const hash = createHash("sha1");
  hash.update(nsBytes);
  hash.update(Buffer.from(name, "utf8"));
  const b = hash.digest().subarray(0, 16);
  b[6] = (b[6] & 0x0f) | 0x50; // version 5
  b[8] = (b[8] & 0x3f) | 0x80; // variant
  const h = b.toString("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}
const nodeUuid = (id) => uuidv5(`${PREFIX}-node:${id}`, NS);
const edgeUuid = (s, t) => uuidv5(`${PREFIX}-edge:${s}->${t}`, NS);

// --- extract NODES / LINKS array literals from the HTML --------------------
const html = readFileSync(SRC, "utf8");
function sliceArray(marker) {
  const start = html.indexOf(marker);
  if (start === -1) throw new Error(`marker not found: ${marker}`);
  const open = html.indexOf("[", start);
  let depth = 0;
  for (let i = open; i < html.length; i++) {
    const c = html[i];
    if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) return html.slice(open, i + 1);
    }
  }
  throw new Error(`unterminated array for ${marker}`);
}
// eslint-disable-next-line no-eval
const NODES = eval(sliceArray("const NODES ="));
// eslint-disable-next-line no-eval
const LINKS = eval(sliceArray("const LINKS ="));

// Category key is stored directly as the node kind; the app palette
// (lib/map/project-graph.ts) maps each kind to a colour + Vietnamese label.
const nodeKind = (cat) => cat || "concept";

// --- edge label -> stored edge kind (colour only; heuristic) ---------------
function edgeKind(label) {
  const l = (label || "").toLowerCase();
  if (/(chủ đầu tư|cổ đông|đầu tư|đạt|cam kết|tác động|theo|quản lý|vận hành|hợp tác|sở hữu|đặt lõi|mảng|tiền thân|chính sách|vĩ mô|bối cảnh|hưởng lợi|động lực)/.test(l))
    return "supports";
  if (/(thuộc|tại|tọa lạc|trong|gồm|mặt tiền|điểm đầu|điểm cuối|hạng|biến thể|cấp bởi|mở rộng|phân khu|phân khúc|dòng|thương hiệu|quy hoạch|kiến trúc|thiết kế|tiện ích|cảnh quan|cụm)/.test(l))
    return "part_of";
  if (/(gần|cạnh|liền kề|lân cận|km|phút|giao|đi qua|kết nối|qua|cửa ngõ|tuyến|nối|tới|điểm đến|liên kết|view|ga)/.test(l))
    return "near";
  return "relates";
}

// --- compose a node note from facts + description + talking point ----------
function stripHtml(s) {
  return (s || "")
    .replace(/<\/(p|li|ul|div)>/gi, " ") // keep word boundaries between blocks
    .replace(/<li[^>]*>/gi, "• ")
    .replace(/<[^>]+>/g, "")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/\s+/g, " ")
    .trim();
}
function composeNote(n) {
  const parts = [];
  if (n.sub) parts.push(n.sub);
  if (n.facts && n.facts.length) {
    parts.push(n.facts.map(([k, v]) => `${k}: ${v}`).join(" · "));
  }
  if (n.desc) parts.push(stripHtml(n.desc));
  if (n.talkpoint) parts.push(`★ Talking point: ${stripHtml(n.talkpoint)}`);
  return parts.join("\n\n");
}

const sqlEsc = (s) => (s == null ? null : String(s).replace(/'/g, "''"));
const val = (s) => (s == null ? "null" : `'${sqlEsc(s)}'`);

// --- build SQL -------------------------------------------------------------
const out = [];
out.push(
  `-- ${PREFIX} knowledge map — generated by scripts/gen_project_map.mjs (do not edit by hand).`,
  "-- Rich per-project Obsidian map. Idempotent: clears this project's map then",
  "-- reinserts with deterministic UUIDv5 ids.",
  "",
  `delete from map_edges where project_id = '${PROJECT_ID}';`,
  `delete from map_nodes where project_id = '${PROJECT_ID}';`,
  "",
  "insert into map_nodes (id, org_id, project_id, label, kind, note) values",
);

const nodeRows = NODES.map(
  (n) =>
    `  ('${nodeUuid(n.id)}','${ORG_ID}','${PROJECT_ID}',${val(n.label)},'${nodeKind(n.cat)}',${val(composeNote(n))})`,
);
out.push(nodeRows.join(",\n") + ";");
out.push("");

// Keep only links whose endpoints exist, de-duplicated.
const ids = new Set(NODES.map((n) => n.id));
const seen = new Set();
const edgeRows = [];
for (const [s, t, label] of LINKS) {
  if (!ids.has(s) || !ids.has(t)) continue;
  const key = `${s}->${t}`;
  if (seen.has(key)) continue;
  seen.add(key);
  edgeRows.push(
    `  ('${edgeUuid(s, t)}','${ORG_ID}','${PROJECT_ID}','${nodeUuid(s)}','${nodeUuid(t)}','${edgeKind(label)}')`,
  );
}
out.push("insert into map_edges (id, org_id, project_id, source_id, target_id, kind) values");
out.push(edgeRows.join(",\n") + ";");
out.push("");

writeFileSync(OUT, out.join("\n"));
console.log(`wrote ${OUT}: ${NODES.length} nodes, ${edgeRows.length} edges`);
