-- 0010 Script Node Engine — library seed (generated from lib/script-engine/data).
-- Regenerate: GEN_SEED=1 npx vitest run lib/script-engine/data/library.test.ts

-- recipes must exist before compat_rules (FK).
insert into recipes (id,name_vi,pillar,preferred_hooks,allowed_hooks,payoff_tags,chain) values
('CT-01','Giới thiệu dự án','Dự án',array['RVL','QUE','PRC']::text[],array['POV','DIR']::text[],array['reveal']::text[],'{"15":[{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"reveal"},{"type":"CTA"}],"30":[{"type":"CTX"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"reveal"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"reveal"},{"type":"CTA"},{"type":"LOOP"}]}'::jsonb),
('CT-02','X tỷ mua được gì / phân tích giá','Giá & ngân sách',array['PRC','QUE']::text[],array['DAT','CMP']::text[],array['answer']::text[],'{"15":[{"type":"BODY_DATA"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"}],"30":[{"type":"BODY_DATA"},{"type":"BODY_COMPARE"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_DATA"},{"type":"BODY_COMPARE"},{"type":"BODY_POINT"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"}]}'::jsonb),
('CT-03','Tour / review thực tế','Dự án',array['POV','RVL','MIR']::text[],array['LUX']::text[],array['reveal','experience']::text[],'{"15":[{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"PAYOFF","deliversTag":"reveal"},{"type":"CTA"}],"30":[{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"PAYOFF","deliversTag":"reveal"},{"type":"CTA"},{"type":"LOOP"}],"60":[{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"PAYOFF","deliversTag":"reveal"},{"type":"CTA"},{"type":"LOOP"}]}'::jsonb),
('CT-04','Kiến thức / pháp lý','Kiến thức',array['FAQ','MYT']::text[],array['TIP','QUE']::text[],array['answer']::text[],'{"15":[{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"}],"30":[{"type":"CTX"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"},{"type":"LOOP"}]}'::jsonb),
('CT-05','Thị trường / số liệu','Thị trường',array['DAT']::text[],array['MYT','QUE']::text[],array['verdict']::text[],'{"15":[{"type":"BODY_DATA"},{"type":"PAYOFF","deliversTag":"verdict"},{"type":"CTA"}],"30":[{"type":"BODY_DATA"},{"type":"BODY_DATA"},{"type":"BODY_OBJECTION"},{"type":"PAYOFF","deliversTag":"verdict"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_DATA"},{"type":"BODY_DATA"},{"type":"BODY_OBJECTION"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"verdict"},{"type":"CTA"}]}'::jsonb),
('CT-06','So sánh A vs B','Thị trường',array['CMP']::text[],array['PRC','QUE']::text[],array['verdict']::text[],'{"15":[{"type":"BODY_COMPARE"},{"type":"PAYOFF","deliversTag":"verdict"},{"type":"CTA"}],"30":[{"type":"BODY_COMPARE"},{"type":"BODY_COMPARE"},{"type":"PAYOFF","deliversTag":"verdict"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_COMPARE"},{"type":"BODY_COMPARE"},{"type":"BODY_COMPARE"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"verdict"},{"type":"CTA"}]}'::jsonb),
('CT-07','Câu chuyện khách hàng','Niềm tin',array['EMO','MIR']::text[],array['POV']::text[],array['transformation']::text[],'{"15":[{"type":"BODY_STORY"},{"type":"PAYOFF","deliversTag":"transformation"},{"type":"CTA"}],"30":[{"type":"BODY_STORY"},{"type":"BODY_STORY"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"transformation"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_STORY"},{"type":"BODY_STORY"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"transformation"},{"type":"CTA"},{"type":"LOOP"}]}'::jsonb),
('CT-08','Sai lầm / cảnh báo','Kiến thức',array['MYT','EMO']::text[],array['FAQ','LST']::text[],array['answer']::text[],'{"15":[{"type":"BODY_OBJECTION"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"}],"30":[{"type":"BODY_OBJECTION"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"},{"type":"LOOP"}],"60":[{"type":"CTX"},{"type":"BODY_OBJECTION"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"answer"},{"type":"CTA"},{"type":"LOOP"}]}'::jsonb),
('CT-09','Lifestyle / trải nghiệm sống','Dự án',array['LUX','POV']::text[],array['TRD']::text[],array['experience']::text[],'{"15":[{"type":"BODY_DEMO"},{"type":"PAYOFF","deliversTag":"experience"},{"type":"CTA"}],"30":[{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"PAYOFF","deliversTag":"experience"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"BODY_DEMO"},{"type":"PAYOFF","deliversTag":"experience"},{"type":"CTA"},{"type":"LOOP"}]}'::jsonb),
('CT-10','Listicle Top-N','Kiến thức',array['LST','TIP']::text[],array['FAQ']::text[],array['list_complete','best']::text[],'{"15":[{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"list_complete"},{"type":"CTA"}],"30":[{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"list_complete"},{"type":"CTA"}],"60":[{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PAYOFF","deliversTag":"list_complete"},{"type":"CTA"},{"type":"LOOP"}]}'::jsonb),
('CT-11','FOMO / tiến độ / sự kiện','Dự án',array['FOMO','DAT']::text[],array['MIR']::text[],array['proof']::text[],'{"15":[{"type":"BODY_DATA"},{"type":"PAYOFF","deliversTag":"proof"},{"type":"CTA"}],"30":[{"type":"BODY_DATA"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"proof"},{"type":"CTA"}],"60":[{"type":"CTX"},{"type":"BODY_DATA"},{"type":"BODY_POINT"},{"type":"PROOF"},{"type":"PAYOFF","deliversTag":"proof"},{"type":"CTA"}]}'::jsonb),
('CT-12','Q&A nhanh (trả lời 1 câu hỏi)','Niềm tin',array['QUE','FAQ']::text[],array['DIR']::text[],array['answer']::text[],'{"15":[{"type":"PAYOFF","deliversTag":"answer"},{"type":"BODY_POINT"},{"type":"CTA"}],"30":[{"type":"PAYOFF","deliversTag":"answer"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"CTA"}],"60":[{"type":"PAYOFF","deliversTag":"answer"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"BODY_POINT"},{"type":"PROOF"},{"type":"CTA"}]}'::jsonb)
on conflict (id) do update set name_vi=excluded.name_vi,pillar=excluded.pillar,preferred_hooks=excluded.preferred_hooks,allowed_hooks=excluded.allowed_hooks,payoff_tags=excluded.payoff_tags,chain=excluded.chain;

insert into hook_templates (id,family,text_template,onscreen_text,visual_directive,duration_min,duration_max,word_min,word_max,requires_slots,optional_slots,promise_tags,tone_tags,platform_fit,risk_level,weight,status) values
('HK-FAQ-01','FAQ','5 câu tôi bị hỏi nhiều nhất về {{loai_hinh}} ở {{khu_vuc}} — trả lời hết trong 1 video.','5 câu hỏi nhiều nhất','Nhìn thẳng cam, giơ 5 ngón',2,4,8,14,array['loai_hinh','khu_vuc']::text[],'{}',array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-FAQ-02','FAQ','Trước khi xuống tiền mua {{loai_hinh}}, bạn bắt buộc phải biết {{so_luong}} điều này.','ĐỌC TRƯỚC KHI CỌC','Đặt bút xuống bàn dứt khoát',2,4,8,14,array['loai_hinh']::text[],array['so_luong']::text[],array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-FAQ-03','FAQ','{{so_luong}} hiểu lầm về {{loai_hinh}} mà 9 trên 10 người mua lần đầu đều dính.','9/10 người dính','Lắc đầu nhẹ, cười',2,4,8,14,array['loai_hinh']::text[],array['so_luong']::text[],array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-FAQ-04','FAQ','Phí bảo trì, phí quản lý, thuế phí — toàn bộ chi phí ẩn khi mua {{du_an}} nằm hết ở đây.','CHI PHÍ ẨN','Xoè quạt hoá đơn giấy',2,4,8,14,array['du_an']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-FAQ-05','FAQ','Khách nhắn tôi: ''{{cau_hoi_kh}}'' — và đây là câu trả lời thật, không né.','trích câu hỏi','Quay màn hình tin nhắn (che tên)',2,4,8,14,array['cau_hoi_kh']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-CMP-01','CMP','{{du_an}} và {{du_an_b}}: cùng tầm {{gia_tu}}, chọn sai là mất luôn khoản chênh vài trăm triệu.','A vs B','Split screen 2 dự án',2,4,8,14,array['du_an','du_an_b','gia_tu']::text[],'{}',array['verdict']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-CMP-02','CMP','Thuê hay mua ở {{khu_vuc}} năm {{nam}}? Tôi tính giúp bạn từng đồng.','THUÊ vs MUA','Cầm máy tính bấm',2,4,8,14,array['khu_vuc']::text[],array['nam']::text[],array['verdict']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-CMP-03','CMP','Căn hộ hay nhà phố với cùng {{gia_tu}}? 3 khác biệt này sẽ quyết định thay bạn.','3 khác biệt','2 tay chỉ 2 hướng',2,4,8,14,array['gia_tu']::text[],'{}',array['verdict']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-CMP-04','CMP','Cùng {{gia_tu}}: bỏ vào {{khu_vuc}} hay {{khu_vuc_b}} thì 5 năm nữa bạn cảm ơn mình?','2 tên khu','Bản đồ 2 vùng highlight',2,4,8,14,array['gia_tu','khu_vuc','khu_vuc_b']::text[],'{}',array['verdict']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-CMP-05','CMP','Đặt 2 căn cạnh nhau là bạn hiểu ngay vì sao căn này đi trước.','Nhìn là hiểu','Chuyển cảnh nhanh 2 căn',2,4,8,14,'{}','{}',array['verdict']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-DAT-01','DAT','{{so_lieu}} — con số này đang âm thầm đổi cục diện {{khu_vuc}}.','số liệu','Con số phóng to chiếm màn hình',2,4,8,14,array['so_lieu','khu_vuc','nguon']::text[],'{}',array['proof']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-DAT-02','DAT','Giá {{khu_vuc}} nhích {{ty_le_tang_gia}} trong {{khoang_tg}} — và lý do thật không phải cái bạn nghĩ.','%','Biểu đồ vẽ tay tăng dần',2,4,8,14,array['khu_vuc','ty_le_tang_gia','khoang_tg','nguon']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-DAT-03','DAT','3 con số phải xem trước khi mua bất kỳ căn nào ở {{khu_vuc}}.','3 con số','Giơ 3 ngón',2,4,8,14,array['khu_vuc','nguon']::text[],'{}',array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-DAT-04','DAT','Lãi suất {{lai_suat}}: mua bây giờ hay chờ thêm? Để số liệu nói thay tôi.','Mua hay chờ?','Chỉ vào bảng lãi suất',2,4,8,14,array['lai_suat','nguon']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-DAT-05','DAT','{{so_lieu}}. Chuyện gì đang xảy ra ở {{du_an}} vậy?','số liệu','Đứng trước dự án, quay ra sau',2,4,8,14,array['so_lieu','du_an','nguon']::text[],'{}',array['proof']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-EMO-01','EMO','Rao {{khoang_tg}} không ai hỏi? Xem hết video này trước khi giảm giá thêm lần nữa.','Đừng vội giảm giá','Tin đăng cũ trên màn hình',2,4,8,14,array['khoang_tg']::text[],'{}',array['answer']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-EMO-02','EMO','Sai lầm này từng khiến khách của tôi mất gần nửa tỷ — đừng để bạn là người tiếp theo.','-500 triệu','Nhìn cam nghiêm túc',2,4,8,14,'{}','{}',array['answer']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-EMO-03','EMO','Vì sao căn nhà ưng ý cứ tuột khỏi tay bạn hết lần này đến lần khác?','Lại trượt nữa…','Cảnh đóng cửa căn hộ, lắc đầu',2,4,8,14,'{}','{}',array['answer']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-EMO-04','EMO','Điều tôi ước có ai đó nói với mình trước khi mua căn nhà đầu tiên.','Ước gì biết sớm','Ngồi xuống, hạ tông giọng',2,4,8,14,'{}','{}',array['answer']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-EMO-05','EMO','Nghĩ mình chưa đủ tiền mua nhà? Câu chuyện này sẽ làm bạn tính lại.','Chưa đủ tiền?','Cầm sổ tiết kiệm/điện thoại app bank',2,4,8,14,'{}','{}',array['transformation']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-RVL-01','RVL','Bên ngoài nhìn {{gia_tu}} là cùng… bên trong thì bạn tự xem đi.','Bên trong = ???','Mở cửa, cam đi theo',2,4,8,14,array['gia_tu']::text[],'{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-RVL-02','RVL','Tôi đổi đúng 1 chi tiết — căn này có chủ sau {{so_ngay}} ngày.','Đổi đúng 1 thứ','Before/after 1 góc phòng',2,4,8,14,array['so_ngay']::text[],'{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-RVL-03','RVL','Căn này có 1 thứ mà ảnh chụp không bao giờ cho bạn thấy.','Ảnh không thấy được','Che ống kính rồi mở',2,4,8,14,'{}','{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-RVL-04','RVL','Chủ nhà để giá thấp hơn thị trường — và 72 giờ sau, chuyện này xảy ra.','72 giờ','Đồng hồ tua nhanh',2,4,8,14,'{}','{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-RVL-05','RVL','Khoản nâng cấp {{so_tien}} này cộng thẳng vào giá bán gấp mấy lần — xem chỗ nào.','{{so_tien}} → x?','Chỉ vào hạng mục nâng cấp',2,4,8,14,array['so_tien']::text[],'{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-POV-01','POV','POV: 6 giờ chiều, bạn vừa về đến căn hộ của mình ở {{du_an}}.','18:00','POV mở cửa, ánh hoàng hôn',2,4,8,14,array['du_an']::text[],'{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-POV-02','POV','Một ngày của sale bất động sản: từ 7 giờ sáng đến lúc khách đặt bút ký cọc.','7AM → ký cọc','Timelapse chuẩn bị đồ',2,4,8,14,'{}','{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-POV-03','POV','Đi cùng tôi xem căn {{loai_can}} view {{view}} tại {{du_an}} — không cắt, không filter.','Tour thật 100%','Bước vào sảnh, vẫy tay',2,4,8,14,array['loai_can','view','du_an']::text[],'{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-POV-04','POV','Chuẩn bị mở bán cùng tôi — hậu trường mà khách không bao giờ thấy.','Behind the scenes','Sắp tài liệu, đeo thẻ',2,4,8,14,'{}','{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-POV-05','POV','Đứng từ tầng {{so_tang}} nhìn xuống — bạn sẽ hiểu vì sao người ta trả tiền cho cái view này.','Tầng {{so_tang}}','Quay từ ban công xuống',2,4,8,14,array['so_tang']::text[],'{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TRD-01','TRD','Cả mạng đang nói về {{su_kien}} — và nó đang diễn ra ngay tại {{khu_vuc}}.','tên trend','Lướt feed rồi ngẩng lên',2,4,8,14,array['su_kien','khu_vuc']::text[],'{}',array['answer']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TRD-02','TRD','Mô tả căn này bằng đúng 1 emoji — tôi chờ dưới comment.','1 emoji = ?','Pan nhanh căn đẹp nhất',2,4,8,14,'{}','{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TRD-03','TRD','Xu hướng nội thất {{nam}}: kiểu này đang chiếm sóng các căn hộ {{khu_vuc}}.','Trend {{nam}}','Cận nội thất theo trend',2,4,8,14,array['khu_vuc']::text[],array['nam']::text[],array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TRD-04','TRD','Căn này tự làm 5 việc trước cả khi bạn về đến nhà.','Smart home','Đèn/rèm tự bật',2,4,8,14,'{}','{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TRD-05','TRD','Vì sao người trẻ đang kéo nhau về {{khu_vuc}}?','Tại sao?','Cảnh phố đông trẻ trung',2,4,8,14,array['khu_vuc']::text[],'{}',array['answer']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LUX-01','LUX','Tiện ích đáng tiền nhất để tiếp khách tại gia — căn này có đủ bộ.','Host tại gia','Bàn ăn/quầy bar đã set',2,4,8,14,'{}','{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LUX-02','LUX','Top {{so_luong}} khu đáng sống nhất {{khu_vuc}} cho người trẻ đang lên.','Top {{so_luong}}','Drone/establishing shot',2,4,8,14,array['khu_vuc']::text[],array['so_luong']::text[],array['list_complete']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LUX-03','LUX','Sống ở đây, mỗi sáng của bạn bắt đầu như thế này.','6:30 AM','Mở rèm đón nắng, pha cà phê',2,4,8,14,'{}','{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LUX-04','LUX','Đẳng cấp không nằm ở giá — nó nằm ở 3 chi tiết này.','3 chi tiết','Cận 1 chi tiết hoàn thiện',2,4,8,14,'{}','{}',array['list_complete']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LUX-05','LUX','Bên trong khu compound kín tiếng nhất {{khu_vuc}}.','Kín tiếng nhất','Cổng an ninh mở chậm',2,4,8,14,array['khu_vuc']::text[],'{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-PRC-01','PRC','{{gia_tu}} mua được gì ở {{khu_vuc}} năm {{nam}}?','{{gia_tu}} = ?','Đứng trước dự án, số tiền phóng to',2,4,8,14,array['gia_tu','khu_vuc']::text[],array['nam']::text[],array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-PRC-02','PRC','Căn {{gia_tu}} và căn {{gia_max}} — khác nhau đúng những gì, tôi chỉ tận nơi.','Chênh bao nhiêu, được gì?','Đi giữa 2 căn',2,4,8,14,array['gia_tu','gia_max']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-PRC-03','PRC','Chi phí ẩn khi mua nhà {{khu_vuc}}: cộng đủ vào, con số sẽ làm bạn giật mình.','+ ??? triệu','Bấm máy tính, dừng tay',2,4,8,14,array['khu_vuc']::text[],'{}',array['reveal']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-PRC-04','PRC','Thu nhập {{thu_nhap}} một tháng thì với được căn nào ở {{khu_vuc}}? Tính thật, không vẽ.','{{thu_nhap}}/tháng','Viết phép tính lên giấy',2,4,8,14,array['thu_nhap','khu_vuc']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-PRC-05','PRC','Hai căn cùng tầng, cùng diện tích — vì sao lệch nhau mấy trăm triệu?','Cùng tầng, lệch giá','Chỉ 2 cửa cạnh nhau',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TIP-01','TIP','Đi xem nhà làm đúng 3 bước này — chủ nhà tự xuống giá cho bạn.','3 bước ép giá lịch sự','Gõ cửa, quay lại nháy mắt',2,4,8,14,'{}','{}',array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TIP-02','TIP','Cắt nửa thời gian rao bán với {{so_luong}} chỉnh sửa chưa tới {{so_tien}}.','Bán nhanh x2','Before/after góc chụp tin đăng',2,4,8,14,array['so_tien']::text[],array['so_luong']::text[],array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TIP-03','TIP','Tự staging căn hộ trước khi đăng tin: 5 việc xong trong 1 buổi sáng.','1 buổi sáng','Timelapse dọn + kê đồ',2,4,8,14,'{}','{}',array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TIP-04','TIP','Trước khi ký hợp đồng mua bán, soi kỹ 4 dòng này đã.','4 dòng sống còn','Lật hợp đồng, highlight',2,4,8,14,'{}','{}',array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-TIP-05','TIP','Đi xem nhà chỉ cần nhớ mang theo đúng 1 thứ này.','1 thứ duy nhất','Bỏ 1 vật vào túi',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LST-01','LST','{{so_luong}} câu bắt buộc phải hỏi trước khi cọc bất kỳ căn nào.','{{so_luong}} câu hỏi','Đếm ngón tay',2,4,8,14,'{}',array['so_luong']::text[],array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LST-02','LST','{{so_luong}} tiện ích phải có nếu bạn mua để cho thuê — thiếu 1 là khó full phòng.','Mua cho thuê?','Lướt qua tiện ích',2,4,8,14,'{}',array['so_luong']::text[],array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LST-03','LST','Tin rao của bạn sẽ tiếp tục ế nếu còn thiếu 3 thứ này.','Vì sao tin ế?','Tin đăng 0 lượt liên hệ',2,4,8,14,'{}','{}',array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LST-04','LST','{{so_luong}} dự án đáng xem nhất {{khu_vuc}} quý này — vị trí cuối ít ai ngờ tới.','Top {{so_luong}}','Map ghim {{so_luong}} điểm',2,4,8,14,array['khu_vuc']::text[],array['so_luong']::text[],array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-LST-05','LST','{{so_luong}} red flag khi đi xem nhà mà ít môi giới nào chỉ cho bạn.','🚩 Red flags','Khoanh đỏ 1 chi tiết',2,4,8,14,'{}',array['so_luong']::text[],array['list_complete']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-QUE-01','QUE','Bạn có bao giờ thắc mắc {{gia_tu}} thì mua được gì ở {{khu_vuc}} chưa?','{{gia_tu}} = ?','Nhún vai hỏi thẳng cam',2,4,8,14,array['gia_tu','khu_vuc']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-QUE-02','QUE','Bây giờ có thật là thời điểm tốt để mua nhà không?','Mua bây giờ?','Nhìn đồng hồ rồi nhìn cam',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-QUE-03','QUE','Đoán giá căn này đi — sai quá 500 triệu thì nhớ follow tôi để khỏi đoán sai lần nữa.','Đoán giá?','Pan căn hộ nhanh',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-QUE-04','QUE','Sai lầm số 1 của người bán nhà trước khi đăng tin là gì?','Sai lầm #1','Giơ ngón trỏ',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-QUE-05','QUE','Căn nhà bạn đang ở — hôm nay thật sự đáng giá bao nhiêu?','Nhà bạn = ?','Chỉ vào cam như chỉ vào nhà người xem',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-DIR-01','DIR','Sắp mua nhà lần đầu ở {{khu_vuc}}? Đứng lại, xem hết video này đã.','Mua lần đầu?','Giơ lòng bàn tay "stop"',2,4,8,14,array['khu_vuc']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-DIR-02','DIR','Ai đang tìm căn {{loai_can}} dưới {{gia_max}} — video này quay cho đúng bạn.','Dưới {{gia_max}}','Chỉ thẳng vào cam',2,4,8,14,array['loai_can','gia_max']::text[],'{}',array['reveal']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-DIR-03','DIR','Định bán nhà trong năm {{nam}}? Xem cái này trước khi gặp bất kỳ môi giới nào.','Chủ nhà nên xem','Ngồi xuống ghế đối diện cam',2,4,8,14,'{}',array['nam']::text[],array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-DIR-04','DIR','Dừng lướt — căn {{loai_can}} này có thể chính là nhà của bạn.','DỪNG LƯỚT','Khung hình đẹp nhất căn',2,4,8,14,array['loai_can']::text[],'{}',array['reveal']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-DIR-05','DIR','Nếu bạn đang cầm {{gia_tu}} và phân vân — tôi nói thẳng cho bạn nghe.','Nói thẳng','Khoanh tay, gật nhẹ',2,4,8,14,array['gia_tu']::text[],'{}',array['verdict']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-MYT-01','MYT','Đừng vội mua nhà gần metro. Nghe vô lý đúng không — xem hết rồi hãy phán.','Đừng mua gần metro?!','Đứng cạnh ga metro',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-MYT-02','MYT','Ai cũng bảo chờ giá giảm. Tôi cho bạn xem con số thật rồi bạn tự quyết.','Chờ giá giảm?','Đặt bảng số liệu lên bàn',2,4,8,14,array['nguon']::text[],'{}',array['verdict']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-MYT-03','MYT','''Mua nhà phải xem hướng'' — đúng, nhưng không phải theo kiểu bạn đang nghĩ.','Hướng nhà ≠ điều bạn nghĩ','Cầm la bàn, lắc đầu cười',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-MYT-04','MYT','9 trên 10 người đi xem nhà sai cách — và rất có thể có cả bạn.','Xem nhà sai cách','Đi vào căn hộ, dừng lại quay ra',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-MYT-05','MYT','Tôi từng khuyên khách đừng mua khu này. Hôm nay tôi rút lại lời đó.','Tôi đã sai','Nhìn xuống rồi nhìn lên cam',2,4,8,14,'{}','{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'medium',1,'active'),
('HK-FOMO-01','FOMO','{{so_can_con_lai}} căn cuối của {{du_an}} — và đây là căn đẹp nhất còn sót lại.','Còn {{so_can_con_lai}} căn','Bảng hàng gạch chéo gần hết',2,4,8,14,array['so_can_con_lai','du_an']::text[],'{}',array['proof']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'high',1,'active'),
('HK-FOMO-02','FOMO','Sau {{moc_tg}}, bảng giá {{du_an}} sẽ không còn như hôm nay — tôi giải thích vì sao.','Trước {{moc_tg}}','Chỉ vào lịch',2,4,8,14,array['moc_tg','du_an','nguon']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'high',1,'active'),
('HK-FOMO-03','FOMO','Tuần trước khách chê đắt. Hôm qua quay lại — căn đó đã có chủ.','Đã có chủ','Mở app gạch tên căn',2,4,8,14,'{}','{}',array['proof']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'high',1,'active'),
('HK-FOMO-04','FOMO','{{su_kien}} sắp khởi động — người nắm tin này đang đi trước phần còn lại một bước.','tên sự kiện','Đứng tại công trường hạ tầng',2,4,8,14,array['su_kien','nguon']::text[],'{}',array['answer']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'high',1,'active'),
('HK-FOMO-05','FOMO','Chính sách {{chinh_sach}} chỉ chạy đến {{moc_tg}} — tôi nói trước để bạn khỏi tiếc.','Hạn: {{moc_tg}}','Đếm ngược trên màn hình',2,4,8,14,array['chinh_sach','moc_tg']::text[],'{}',array['proof']::text[],array['chuyen_gia','than_thien']::text[],array['tiktok','reels','shorts']::text[],'high',1,'active'),
('HK-MIR-01','MIR','Ngay sau cánh cửa này là lý do căn này chênh mấy trăm triệu so với căn sát vách.','Sau cánh cửa này…','Tay đang xoay nắm cửa (mở giữa hành động)',2,4,8,14,'{}','{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-MIR-02','MIR','Đây — chính là khoảnh khắc đáng nhất của cái nghề này.','','Đang trao chìa khoá cho khách',2,4,8,14,'{}','{}',array['experience']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-MIR-03','MIR','Chủ đầu tư nói {{dien_tich}}. Để tôi đo cho bạn xem có đúng không.','{{dien_tich}} thật không?','Đang bấm thước laser',2,4,8,14,array['dien_tich']::text[],'{}',array['proof']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-MIR-04','MIR','Tiến độ {{du_an}} hôm nay, ngày {{ngay}} — không chỉnh, không filter.','ngày tháng','Đang đi giữa công trường, mũ bảo hộ',2,4,8,14,array['du_an']::text[],array['ngay']::text[],array['proof']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active'),
('HK-MIR-05','MIR','Dòng này trong hợp đồng từng cứu khách tôi một khoản rất lớn.','Dòng số …','Đang lật trang, highlight 1 dòng',2,4,8,14,'{}','{}',array['reveal']::text[],array['than_thien','ke_chuyen']::text[],array['tiktok','reels','shorts']::text[],'low',1,'active')
on conflict (id) do update set family=excluded.family,text_template=excluded.text_template,onscreen_text=excluded.onscreen_text,visual_directive=excluded.visual_directive,duration_min=excluded.duration_min,duration_max=excluded.duration_max,word_min=excluded.word_min,word_max=excluded.word_max,requires_slots=excluded.requires_slots,optional_slots=excluded.optional_slots,promise_tags=excluded.promise_tags,tone_tags=excluded.tone_tags,platform_fit=excluded.platform_fit,risk_level=excluded.risk_level,weight=excluded.weight,status=excluded.status;

insert into node_templates (id,node_type,text_template,onscreen_text,visual_directive,duration_min,duration_max,word_min,word_max,requires_slots,optional_slots,delivers_tag,funnel,tone_tags,platform_fit,weight,status) values
('CTX-01','CTX','Nếu bạn đang {{noi_dau}}, thì video này quay đúng cho bạn.','Dành cho bạn','Nhìn thẳng cam, hạ giọng đồng cảm',2,4,8,14,'{}','{}',null,null,'{}','{}',1,'active'),
('CTX-02','CTX','Tôi là {{ten_sale}}, {{so_nam_kn}} năm chuyên {{khu_vuc_chuyen}}, hơn {{so_giao_dich}} giao dịch.','{{so_nam_kn}} năm · {{so_giao_dich}} giao dịch','Cận mặt tự tin, có thể chèn ảnh thành tích',2,4,8,14,array['so_nam_kn','so_giao_dich']::text[],'{}',null,null,'{}','{}',1,'active'),
('CTX-03','CTX','Quyết sai ở đúng bước này, cái giá phải trả là {{hau_qua}}.','Cẩn thận bước này','Nhíu mày, nhịp chậm lại',2,4,8,14,'{}','{}',null,null,'{}','{}',1,'active'),
('CTX-04','CTX','Trong {{thoi_luong}} giây tới, bạn sẽ biết chính xác {{loi_hua}}.','{{thoi_luong}}s','Giơ ngón đếm ngược',2,4,8,14,'{}','{}',null,null,'{}','{}',1,'active'),
('CTX-05','CTX','Video này dành cho người có tầm {{ngan_sach}} và đang cần {{nhu_cau}}.','Tầm {{ngan_sach}}','Chỉ vào cam, lọc đối tượng',2,4,8,14,array['ngan_sach']::text[],'{}',null,null,'{}','{}',1,'active'),
('CTX-06','CTX','Bối cảnh nhanh: {{boi_canh_ngan}}. Vì vậy chuyện này mới quan trọng.','Bối cảnh','B-roll thị trường/khu vực',2,4,8,14,'{}','{}',null,null,'{}','{}',1,'active'),
('CTX-07','CTX','Không vòng vo — vào thẳng vấn đề.','Vào thẳng','Cắt nhanh, nhịp dứt khoát',2,3,6,10,'{}','{}',null,null,'{}','{}',1,'active'),
('CTX-08','CTX','Tuần trước, một khách của tôi {{tinh_huong_ngan}}. Và đó là lý do có video này.','Chuyện tuần trước','Hồi tưởng, ánh mắt kể chuyện',2,4,8,14,'{}','{}',null,null,'{}','{}',1,'active'),
('BP-C1','BODY_POINT','Thứ {{n}}: {{y_chinh}}. {{vi_sao_quan_trong}}.','{{y_chinh}}','Đổi góc máy / B-roll minh hoạ đúng ý; overlay = từ khoá ≤5 từ',5,8,16,26,'{}','{}',null,null,'{}','{}',1,'active'),
('BP-C2','BODY_POINT','Điều ít ai nói với bạn: {{y_chinh}}. {{vi_sao_quan_trong}}.','{{y_chinh}}','Nghiêng người, hạ giọng tiết lộ; B-roll minh hoạ',5,8,16,26,'{}','{}',null,null,'{}','{}',1,'active'),
('BP-C3','BODY_POINT','Tiếp theo — và cái này quan trọng hơn: {{y_chinh}}. {{vi_sao_quan_trong}}.','{{y_chinh}}','Cắt cảnh mới, nhấn nhịp; B-roll minh hoạ',5,8,16,26,'{}','{}',null,null,'{}','{}',1,'active'),
('BP-C4','BODY_POINT','Đây mới là điểm ăn tiền: {{y_chinh}}. {{vi_sao_quan_trong}}.','{{y_chinh}}','Zoom nhẹ vào chi tiết; B-roll minh hoạ',5,8,16,26,'{}','{}',null,null,'{}','{}',1,'active'),
('BP-C5','BODY_POINT','Số {{n}}, nghe kỹ nè: {{y_chinh}}. {{vi_sao_quan_trong}}.','{{y_chinh}}','Chỉ tay vào overlay số; B-roll minh hoạ',5,8,16,26,'{}','{}',null,null,'{}','{}',1,'active'),
('BD-01','BODY_DATA','{{con_so}}. Nghĩa là {{dien_giai}}. Với bạn, điều đó tức là {{tac_dong}}.','{{con_so}}','Con số hiện to giữa khung; nguồn chữ nhỏ góc phải',5,8,18,28,array['nguon']::text[],'{}',null,null,'{}','{}',1,'active'),
('BD-02','BODY_DATA','So với {{moc_so_sanh}}, {{chu_the}} đang {{xu_huong}} khoảng {{ty_le}}.','{{ty_le}}','Biểu đồ 2 cột so sánh; nguồn góc dưới',5,8,16,26,array['moc_so_sanh','nguon']::text[],'{}',null,null,'{}','{}',1,'active'),
('BD-03','BODY_DATA','Quy hết ra tiền: {{phep_tinh_ngan}} — ra đúng {{ket_qua}}.','{{ket_qua}}','Viết phép tính lên màn hình / máy tính bấm',5,8,14,22,'{}','{}',null,null,'{}','{}',1,'active'),
('BD-04','BODY_DATA','Số liệu từ {{nguon}}: {{con_so}} — tôi để nguyên ảnh chụp trên màn hình cho bạn tự kiểm.','{{con_so}}','Chụp màn hình báo cáo gốc, khoanh số',5,8,16,26,array['nguon']::text[],'{}',null,null,'{}','{}',1,'active'),
('BS-01','BODY_STORY','Khách tôi — {{chan_dung_ngan}} — từng {{tro_ngai}}. Bọn tôi {{hanh_dong}}. Kết quả: {{ket_qua}}.','Chuyện thật','Dựng lại cảnh / ảnh tư liệu che mặt khách',7,10,24,34,'{}','{}',null,null,'{}','{}',1,'active'),
('BS-02','BODY_STORY','Ngày {{moc_tg}}: {{su_kien_1}}. {{khoang_tg}} sau: {{su_kien_2}}. Khác biệt nằm ở {{bai_hoc}}.','Trước → Sau','Timeline 2 mốc, before/after',7,10,22,32,'{}','{}',null,null,'{}','{}',1,'active'),
('BS-03','BODY_STORY','Lúc đó ai cũng nói {{y_kien_so_dong}}. Khách tôi làm ngược lại — và {{ket_qua}}.','Làm ngược số đông','Cảnh đám đông vs cá nhân, tương phản',7,10,22,32,'{}','{}',null,null,'{}','{}',1,'active'),
('BDM-01','BODY_DEMO','Đây là {{khu_vuc_can}} — để ý {{diem_nhan}}. {{chi_tiet_cam_quan}}.','{{khu_vuc_can}}','Walk-in quay {{khu_vuc_can}}, pan tới điểm nhấn',5,8,16,26,'{}','{}',null,null,'{}','{}',1,'active'),
('BDM-02','BODY_DEMO','Bước vào {{khu_vuc_can}}: {{kich_thuoc}}, hướng {{huong}} — và chỗ bạn cần soi kỹ là {{diem_check}}.','{{huong}} · {{kich_thuoc}}','Bước vào không gian, lia toàn cảnh rồi cận điểm cần soi',5,8,18,28,'{}','{}',null,null,'{}','{}',1,'active'),
('BDM-03','BODY_DEMO','Chỗ này mọi người hay lướt qua — nhưng {{vi_tri}} mới quyết định trải nghiệm sống hằng ngày.','Đừng bỏ qua','Dừng lại ở chi tiết dễ bị bỏ qua, cận cảnh',5,8,16,26,'{}','{}',null,null,'{}','{}',1,'active'),
('BDM-04','BODY_DEMO','[Quay cận] {{vat_lieu_hoan_thien}} — loại này {{danh_gia_ngan}}.','{{vat_lieu_hoan_thien}}','Macro/cận vật liệu hoàn thiện, chạm tay vào',5,8,12,20,'{}','{}',null,null,'{}','{}',1,'active'),
('BC-01','BODY_COMPARE','Cùng tiêu chí {{tieu_chi}}: {{ben_a}} được {{diem_a}}, còn {{ben_b}} là {{diem_b}}.','{{ben_a}} vs {{ben_b}}','Split-screen hoặc bảng 2 cột overlay',6,9,18,28,'{}','{}',null,null,'{}','{}',1,'active'),
('BC-02','BODY_COMPARE','Khác biệt lớn nhất không phải {{thu_de_thay}} — mà là {{thu_quyet_dinh}}.','Khác biệt thật','Gạt yếu tố hiển nhiên sang bên, nhấn yếu tố quyết định',6,9,14,24,'{}','{}',null,null,'{}','{}',1,'active'),
('BC-03','BODY_COMPARE','Bạn ưu tiên {{uu_tien_1}} → chọn {{ben_a}}. Ưu tiên {{uu_tien_2}} → {{ben_b}}. Đơn giản vậy.','Chọn theo ưu tiên','Sơ đồ rẽ nhánh 2 hướng overlay',6,9,18,28,'{}','{}',null,null,'{}','{}',1,'active'),
('BO-01','BODY_OBJECTION','Nhiều người nghĩ {{ngo_nhan}}. Thực tế: {{su_that}}.','Ngộ nhận vs Sự thật','Text ''Ngộ nhận'' gạch chéo → ''Sự thật''',5,8,12,22,'{}','{}',null,null,'{}','{}',1,'active'),
('BO-02','BODY_OBJECTION','''{{phan_doi_thuong_gap}}'' — câu này tôi nghe mỗi tuần. Đây là góc nhìn khác:','Góc nhìn khác','Nhại lại lời phản đối rồi lật lại',5,8,14,24,'{}','{}',null,null,'{}','{}',1,'active'),
('BO-03','BODY_OBJECTION','Đúng là {{nhuoc_diem_thua_nhan}}. Nhưng đổi lại, bạn được {{loi_ich_bu_dap}}.','Đánh đổi','Cân 2 bên: nhược điểm ↔ lợi ích',5,8,14,24,'{}','{}',null,null,'{}','{}',1,'active'),
('BO-04','BODY_OBJECTION','Rủi ro lớn nhất không phải {{rui_ro_tuong_tuong}} — mà là {{rui_ro_that}}.','Rủi ro thật','Gạt rủi ro tưởng tượng, nhấn rủi ro thật',5,8,14,24,'{}','{}',null,null,'{}','{}',1,'active'),
('PRF-01','PROOF','{{so_giao_dich}} giao dịch ngay tại {{khu_vuc}} trong {{khoang_tg}} — không phải lý thuyết.','{{so_giao_dich}} giao dịch','Lướt ảnh ký kết/bàn giao đã che thông tin',4,6,12,20,array['so_giao_dich']::text[],'{}',null,null,'{}','{}',1,'active'),
('PRF-02','PROOF','Khách gần nhất của tôi: {{ket_qua_khach}} — tin nhắn thật trên màn hình, tôi che tên.','Tin nhắn thật','Quay màn hình tin nhắn, che danh tính',4,6,12,20,'{}','{}',null,null,'{}','{}',1,'active'),
('PRF-03','PROOF','Pháp lý: {{phap_ly}} — giấy tờ tôi đang cầm trên tay đây.','{{phap_ly}}','Cầm giấy tờ pháp lý đưa lên cam',4,6,10,18,array['phap_ly']::text[],'{}',null,null,'{}','{}',1,'active'),
('PRF-04','PROOF','{{cdt}} đã bàn giao {{so_du_an_ban_giao}} dự án đúng hạn — track record kiểm chứng được.','Track record CĐT','Ảnh các dự án đã bàn giao của CĐT',4,6,12,20,'{}','{}',null,null,'{}','{}',1,'active'),
('PRF-05','PROOF','Toàn bộ số liệu lấy từ {{nguon}} — không phải tôi tự nói.','Nguồn: {{nguon}}','Hiện logo/ảnh báo cáo nguồn',4,6,10,18,array['nguon']::text[],'{}',null,null,'{}','{}',1,'active'),
('PAY-01','PAYOFF','Và đây — chính là {{cai_duoc_hua}}.','Đây!','Reveal đúng thứ đã hứa ở hook',3,5,8,14,'{}','{}','reveal',null,'{}','{}',1,'active'),
('PAY-02','PAYOFF','Chốt: nếu là tiền của tôi, tôi chọn {{lua_chon}} — vì {{ly_do_1cau}}.','Chốt','Nhìn thẳng cam, gật dứt khoát',3,5,12,18,'{}','{}','verdict',null,'{}','{}',1,'active'),
('PAY-03','PAYOFF','Câu trả lời: {{dap_an}}. Gọn vậy thôi.','Đáp án','Nhìn thẳng cam, gật nhẹ',3,5,8,14,'{}','{}','answer',null,'{}','{}',1,'active'),
('PAY-04','PAYOFF','Từ {{trang_thai_truoc}} thành {{trang_thai_sau}} — trong đúng {{khoang_tg}}.','Trước → Sau','Before/after dứt khoát',3,5,10,16,'{}','{}','transformation',null,'{}','{}',1,'active'),
('PAY-05','PAYOFF','Và số {{vi_tri}} — {{lua_chon_tot_nhat}} — giờ thì bạn hiểu vì sao rồi đó.','#1','Chốt vị trí top của danh sách',3,5,10,16,'{}','{}','list_complete',null,'{}','{}',1,'active'),
('PAY-06','PAYOFF','Nhưng thứ đáng giá nhất lại không nằm trong những gì tôi vừa kể — mà là {{twist}}.','Twist','Hạ giọng, tiết lộ cú twist cuối',3,5,12,18,'{}','{}','proof',null,'{}','{}',1,'active'),
('PAY-07','PAYOFF','Và đó là cảm giác mỗi ngày khi bạn sống ở đây.','Cảm giác sống','Cảnh sống chậm, ánh sáng đẹp',3,5,8,14,'{}','{}','experience',null,'{}','{}',1,'active'),
('CTA-01','CTA','Comment ''{{tu_khoa_cmt}}'' — tôi gửi bạn {{qua_tang}} qua tin nhắn, miễn phí.','💬 {{tu_khoa_cmt}}','Chỉ xuống ô comment',3,5,12,18,'{}','{}',null,'lead_keyword','{}','{}',1,'active'),
('CTA-02','CTA','Lưu video này — lúc đi xem nhà mở ra check từng mục.','🔖 Lưu lại','Tay chạm icon lưu',3,5,10,16,'{}','{}',null,'save','{}','{}',1,'active'),
('CTA-03','CTA','Follow để xem phần {{phan_tiep}}: {{noi_dung_phan_sau}}.','Phần {{phan_tiep}}','Chỉ nút follow',3,5,8,14,'{}','{}',null,'follow_series','{}','{}',1,'active'),
('CTA-04','CTA','Inbox tôi chữ ''{{tu_khoa_cmt}}'' kèm ngân sách — tôi lọc căn phù hợp, không phí gì cả.','📩 {{tu_khoa_cmt}}','Chỉ icon nhắn tin',3,5,12,20,'{}','{}',null,'lead_dm','{}','{}',1,'active'),
('CTA-05','CTA','Gửi video này cho người sắp mua nhà mà bạn quý.','↗ Gửi tặng','Tay chạm icon share',3,5,8,14,'{}','{}',null,'share','{}','{}',1,'active'),
('CTA-06','CTA','Bạn chọn {{lua_chon_a}} hay {{lua_chon_b}}? Comment đi, tôi đọc hết.','{{lua_chon_a}} / {{lua_chon_b}}','Giơ 2 tay 2 lựa chọn',3,5,10,16,'{}','{}',null,'engagement','{}','{}',1,'active'),
('CTA-07','CTA','Lịch xem nhà cuối tuần này còn {{so_slot}} slot — đặt ở {{kenh_dat}}.','Còn {{so_slot}} slot','Chỉ vào lịch/bio',3,5,10,16,'{}','{}',null,'booking','{}','{}',1,'active'),
('CTA-08','CTA','Còn thắc mắc gì về {{chu_de}}, để lại câu hỏi — video sau tôi trả lời.','Hỏi mình nhé','Mở lòng bàn tay mời hỏi',3,5,10,16,'{}','{}',null,'soft','{}','{}',1,'active'),
('CTA-09','CTA','Bảng giá và mặt bằng đầy đủ, tôi để hết ở trang cá nhân.','Xem ở trang cá nhân','Chỉ lên avatar/bio',3,5,10,16,'{}','{}',null,'profile','{}','{}',1,'active'),
('CTA-10','CTA','Thấy có ích thì follow — còn muốn nhận {{tai_lieu}} thì comment ''{{tu_khoa_cmt}}''.','Follow + 💬 {{tu_khoa_cmt}}','Chỉ nút follow rồi ô comment',3,5,12,20,'{}','{}',null,'dual','{}','{}',1,'active'),
('LP-01','LOOP','Giờ quay lại câu hỏi đầu video — bạn đã có câu trả lời chưa?','Quay lại đầu','Cắt về đúng khung hình mở đầu',1,2,8,14,'{}','{}',null,null,'{}','{}',1,'active'),
('LP-02','LOOP','Và đó là lý do tôi nói câu đầu tiên.','','Cắt về khung mở đầu, gật đầu',1,2,6,12,'{}','{}',null,null,'{}','{}',1,'active'),
('LP-03','LOOP','[Cắt về đúng khung hình mở đầu] + im lặng 1 nhịp, gật đầu.','','Loop hình mở đầu, im lặng 1 nhịp',1,2,0,0,'{}','{}',null,null,'{}','{}',1,'active'),
('LP-04','LOOP','Xem lại từ đầu đi — đáp án tôi đã nhá ngay giây thứ hai.','Xem lại nhé','Cắt về giây thứ 2 của video',1,2,8,14,'{}','{}',null,null,'{}','{}',1,'active')
on conflict (id) do update set node_type=excluded.node_type,text_template=excluded.text_template,onscreen_text=excluded.onscreen_text,visual_directive=excluded.visual_directive,duration_min=excluded.duration_min,duration_max=excluded.duration_max,word_min=excluded.word_min,word_max=excluded.word_max,requires_slots=excluded.requires_slots,optional_slots=excluded.optional_slots,delivers_tag=excluded.delivers_tag,funnel=excluded.funnel,tone_tags=excluded.tone_tags,platform_fit=excluded.platform_fit,weight=excluded.weight,status=excluded.status;

insert into compat_rules (hook_family,content_type,level) values
('FAQ','CT-01','allowed'),
('FAQ','CT-02','allowed'),
('FAQ','CT-03','blocked'),
('FAQ','CT-04','preferred'),
('FAQ','CT-05','allowed'),
('FAQ','CT-06','allowed'),
('FAQ','CT-07','blocked'),
('FAQ','CT-08','allowed'),
('FAQ','CT-09','blocked'),
('FAQ','CT-10','allowed'),
('FAQ','CT-11','blocked'),
('FAQ','CT-12','preferred'),
('CMP','CT-01','allowed'),
('CMP','CT-02','allowed'),
('CMP','CT-03','blocked'),
('CMP','CT-04','allowed'),
('CMP','CT-05','allowed'),
('CMP','CT-06','preferred'),
('CMP','CT-07','blocked'),
('CMP','CT-08','allowed'),
('CMP','CT-09','blocked'),
('CMP','CT-10','allowed'),
('CMP','CT-11','blocked'),
('CMP','CT-12','allowed'),
('DAT','CT-01','allowed'),
('DAT','CT-02','allowed'),
('DAT','CT-03','blocked'),
('DAT','CT-04','allowed'),
('DAT','CT-05','preferred'),
('DAT','CT-06','allowed'),
('DAT','CT-07','blocked'),
('DAT','CT-08','allowed'),
('DAT','CT-09','blocked'),
('DAT','CT-10','allowed'),
('DAT','CT-11','preferred'),
('DAT','CT-12','allowed'),
('EMO','CT-01','allowed'),
('EMO','CT-02','blocked'),
('EMO','CT-03','allowed'),
('EMO','CT-04','allowed'),
('EMO','CT-05','blocked'),
('EMO','CT-06','blocked'),
('EMO','CT-07','preferred'),
('EMO','CT-08','preferred'),
('EMO','CT-09','allowed'),
('EMO','CT-10','blocked'),
('EMO','CT-11','blocked'),
('EMO','CT-12','allowed'),
('RVL','CT-01','preferred'),
('RVL','CT-02','allowed'),
('RVL','CT-03','preferred'),
('RVL','CT-04','blocked'),
('RVL','CT-05','blocked'),
('RVL','CT-06','allowed'),
('RVL','CT-07','allowed'),
('RVL','CT-08','allowed'),
('RVL','CT-09','allowed'),
('RVL','CT-10','blocked'),
('RVL','CT-11','allowed'),
('RVL','CT-12','blocked'),
('POV','CT-01','allowed'),
('POV','CT-02','blocked'),
('POV','CT-03','preferred'),
('POV','CT-04','blocked'),
('POV','CT-05','blocked'),
('POV','CT-06','blocked'),
('POV','CT-07','allowed'),
('POV','CT-08','blocked'),
('POV','CT-09','preferred'),
('POV','CT-10','blocked'),
('POV','CT-11','allowed'),
('POV','CT-12','blocked'),
('TRD','CT-01','allowed'),
('TRD','CT-02','allowed'),
('TRD','CT-03','allowed'),
('TRD','CT-04','blocked'),
('TRD','CT-05','allowed'),
('TRD','CT-06','blocked'),
('TRD','CT-07','blocked'),
('TRD','CT-08','blocked'),
('TRD','CT-09','allowed'),
('TRD','CT-10','allowed'),
('TRD','CT-11','allowed'),
('TRD','CT-12','blocked'),
('LUX','CT-01','allowed'),
('LUX','CT-02','allowed'),
('LUX','CT-03','allowed'),
('LUX','CT-04','blocked'),
('LUX','CT-05','blocked'),
('LUX','CT-06','blocked'),
('LUX','CT-07','blocked'),
('LUX','CT-08','blocked'),
('LUX','CT-09','preferred'),
('LUX','CT-10','allowed'),
('LUX','CT-11','blocked'),
('LUX','CT-12','blocked'),
('PRC','CT-01','preferred'),
('PRC','CT-02','preferred'),
('PRC','CT-03','allowed'),
('PRC','CT-04','allowed'),
('PRC','CT-05','allowed'),
('PRC','CT-06','allowed'),
('PRC','CT-07','blocked'),
('PRC','CT-08','allowed'),
('PRC','CT-09','allowed'),
('PRC','CT-10','allowed'),
('PRC','CT-11','allowed'),
('PRC','CT-12','allowed'),
('TIP','CT-01','blocked'),
('TIP','CT-02','allowed'),
('TIP','CT-03','blocked'),
('TIP','CT-04','allowed'),
('TIP','CT-05','blocked'),
('TIP','CT-06','blocked'),
('TIP','CT-07','blocked'),
('TIP','CT-08','allowed'),
('TIP','CT-09','blocked'),
('TIP','CT-10','preferred'),
('TIP','CT-11','blocked'),
('TIP','CT-12','allowed'),
('LST','CT-01','allowed'),
('LST','CT-02','allowed'),
('LST','CT-03','allowed'),
('LST','CT-04','allowed'),
('LST','CT-05','allowed'),
('LST','CT-06','blocked'),
('LST','CT-07','blocked'),
('LST','CT-08','allowed'),
('LST','CT-09','allowed'),
('LST','CT-10','preferred'),
('LST','CT-11','blocked'),
('LST','CT-12','blocked'),
('QUE','CT-01','preferred'),
('QUE','CT-02','preferred'),
('QUE','CT-03','allowed'),
('QUE','CT-04','allowed'),
('QUE','CT-05','allowed'),
('QUE','CT-06','allowed'),
('QUE','CT-07','allowed'),
('QUE','CT-08','allowed'),
('QUE','CT-09','allowed'),
('QUE','CT-10','allowed'),
('QUE','CT-11','allowed'),
('QUE','CT-12','preferred'),
('DIR','CT-01','allowed'),
('DIR','CT-02','allowed'),
('DIR','CT-03','allowed'),
('DIR','CT-04','allowed'),
('DIR','CT-05','blocked'),
('DIR','CT-06','blocked'),
('DIR','CT-07','allowed'),
('DIR','CT-08','allowed'),
('DIR','CT-09','allowed'),
('DIR','CT-10','allowed'),
('DIR','CT-11','allowed'),
('DIR','CT-12','allowed'),
('MYT','CT-01','blocked'),
('MYT','CT-02','allowed'),
('MYT','CT-03','blocked'),
('MYT','CT-04','preferred'),
('MYT','CT-05','allowed'),
('MYT','CT-06','allowed'),
('MYT','CT-07','allowed'),
('MYT','CT-08','preferred'),
('MYT','CT-09','blocked'),
('MYT','CT-10','allowed'),
('MYT','CT-11','blocked'),
('MYT','CT-12','allowed'),
('FOMO','CT-01','allowed'),
('FOMO','CT-02','blocked'),
('FOMO','CT-03','allowed'),
('FOMO','CT-04','blocked'),
('FOMO','CT-05','allowed'),
('FOMO','CT-06','blocked'),
('FOMO','CT-07','blocked'),
('FOMO','CT-08','blocked'),
('FOMO','CT-09','blocked'),
('FOMO','CT-10','blocked'),
('FOMO','CT-11','preferred'),
('FOMO','CT-12','blocked'),
('MIR','CT-01','allowed'),
('MIR','CT-02','allowed'),
('MIR','CT-03','preferred'),
('MIR','CT-04','allowed'),
('MIR','CT-05','allowed'),
('MIR','CT-06','allowed'),
('MIR','CT-07','preferred'),
('MIR','CT-08','allowed'),
('MIR','CT-09','allowed'),
('MIR','CT-10','blocked'),
('MIR','CT-11','allowed'),
('MIR','CT-12','allowed')
on conflict (hook_family,content_type) do update set level=excluded.level;

insert into slot_registry (key,slot_group,data_type,source_path,formatter,computed_formula,fallback_text,requires_source) values
('du_an','project','text','project.name',null,null,null,false),
('cdt','project','text','developer.name',null,null,'chủ đầu tư',false),
('khu_vuc','project','text','project.locationText',null,null,'khu vực này',false),
('khu_vuc_b','project','text',null,null,null,'khu vực khác',false),
('du_an_b','project','text',null,null,null,'một dự án khác',false),
('loai_hinh','project','enum',null,null,null,'bất động sản',false),
('loai_can','project','text',null,null,'bedrooms + wc + area','căn này',false),
('gia_tu','project','currency','project.priceMin','fmt_ty',null,'tầm giá này',false),
('gia_max','project','currency','project.priceMax','fmt_ty',null,null,false),
('gia_m2','project','currency',null,'fmt_trieu','price/area',null,false),
('dien_tich','project','number',null,'fmt_m2',null,null,false),
('view','project','text',null,null,null,'view đẹp',false),
('so_tang','project','number',null,null,null,null,false),
('ban_giao','project','date',null,'fmt_quy',null,null,false),
('phap_ly','project','enum',null,null,null,null,false),
('usp_1','project','text',null,null,null,null,false),
('usp_2','project','text',null,null,null,null,false),
('usp_3','project','text',null,null,null,null,false),
('tien_ich_hot','project','text',null,null,null,null,false),
('chinh_sach','project','text',null,null,null,null,false),
('chiet_khau','project','text',null,null,null,null,false),
('so_can_con_lai','project','number',null,null,null,null,false),
('tien_do','project','text',null,null,null,null,false),
('lai_suat','market','number',null,'fmt_pct',null,null,true),
('ty_le_tang_gia','market','number',null,'fmt_pct',null,null,true),
('khoang_tg','market','text',null,null,null,'thời gian gần đây',false),
('so_lieu','market','text',null,null,null,null,true),
('nguon','market','text',null,null,null,null,true),
('moc_so_sanh','market','text',null,null,null,null,true),
('su_kien','market','text',null,null,null,null,true),
('ten_sale','agent','text','branding.displayName',null,null,'tôi',false),
('so_nam_kn','agent','number','branding.soNamKn',null,null,null,false),
('so_giao_dich','agent','number','branding.soGiaoDich',null,null,null,false),
('khu_vuc_chuyen','agent','text','branding.khuVucChuyen',null,null,'bất động sản khu vực này',false),
('kenh_dat','agent','text','branding.kenhDat',null,null,'link ở bio',false),
('chan_dung_kh','audience','text',null,null,null,'người mua nhà',false),
('noi_dau','audience','text',null,null,null,'đang phân vân chọn nhà',false),
('ngan_sach','audience','currency',null,'fmt_ty',null,null,false),
('thu_nhap','audience','currency',null,'fmt_trieu',null,null,false),
('tu_khoa_cmt','audience','keyword',null,null,null,'GIÁ',false),
('qua_tang','audience','text',null,null,null,'bảng giá mới nhất',false),
('tai_lieu','audience','text',null,null,null,'tài liệu hữu ích',false),
('cau_hoi_kh','audience','text',null,null,null,'câu hỏi thường gặp',false),
('chu_de','audience','text',null,null,null,'chủ đề này',false),
('so_ngay','format','number',null,null,null,'vài',false),
('so_tien','project','currency',null,'fmt_trieu',null,'khoản này',false),
('moc_tg','project','text',null,null,null,'thời điểm này',false),
('so_slot','format','number',null,null,null,'vài',false),
('so_luong','format','number',null,null,null,null,false),
('nam','format','date',null,null,null,null,false),
('thang','format','date',null,null,null,null,false),
('ngay','format','date',null,null,null,null,false),
('thoi_luong','format','number',null,null,null,null,false),
('n','format','number',null,null,null,null,false),
('tu_khoa_seo','format','text',null,null,null,null,false)
on conflict (key) do update set slot_group=excluded.slot_group,data_type=excluded.data_type,source_path=excluded.source_path,formatter=excluded.formatter,computed_formula=excluded.computed_formula,fallback_text=excluded.fallback_text,requires_source=excluded.requires_source;
